### ISSUE TITLE
StockMaster

### ISSUE THREAD

**Issue by xTYx728** [alainbryden/bitburner-scripts#10]
Dont know if its an issue on my end or not. Have everything bought and shorting gets instantly disabled in 2 seconds upon launching. 
![image](https://user-images.githubusercontent.com/889918/147425627-b775a4d4-2ba9-4ece-bde7-78d9119868af.png)

**Comment by alainbryden** [comment]
If you haven't unlocked shorts yet, you can't use them.

**Comment by xTYx728** [comment]
oh !@#$ okay. I thought I unlocked it... thank you man
