### ISSUE TITLE
work-for-faction.js: Working for corpo even with --crime-focus

### ISSUE THREAD

**Issue by Evanito** [alainbryden/bitburner-scripts#100]
![image](https://user-images.githubusercontent.com/5620666/164642701-3fd40dd3-8560-41c0-94a3-c5bd32ce7910.png)
Running autopilot.js on BN1, I have SF2 so it is trying to get enough karma, but every once in a while (after it meets an invite requirement usually) I catch it working for a corpo for some reason. 
At the time of this screenshot, I have -14k karma.

Is this intentional behavior?

**Comment by alainbryden** [comment]
`work-for-factions` doesn't technically have a mode that just does crime just for the sake of doing crime - it is only doing it to meet the minimum combat requirements to get into a faction of interest. --crime-focus merely changes the priority faction order to first try to get into all crime factions before going back to all other factions.

If the next faction it wants to join requires 100 of each stat, and it thinks it can train to that in a sensible amount of time, then it will train all the way to 100. If the faction after that requires 200 of each stat, and it thinks that will take too long, it won't spend a second training and will move on to some other faction.

Hope that makes sense.

So all that said, there is a setting `training-stat-per-multi-threshold` which defaults to a value of `100`. This basically says, with default str/str_exp multis of 1, it will only attempt to train you up to 100 str, anything else will probably take too much time. Once you get some augs boosting your stats (e.g. 2.0 str * 2.0 exp = 4.0) then it'll be willing to try and train up to 400, etc... I've tried to ameliorate the above situation by having autopilot.js call it with a --training-stat-per-multi-threshold of 200, which should at least have it doing crime until it's got 200 of each stat to meet "The Syndicate" combat stat requirements.

If this still isn't sufficient, then perhaps I can add logic to kill work-for-factions.js and call crime.js instead, but in my experiements, it's been sufficient (with the help of sleeves also grinding for Karma).
