### ISSUE TITLE
autopilot.js: losing --enable-bladeburner flag after installing augs

### ISSUE THREAD

**Issue by stedel** [alainbryden/bitburner-scripts#101]
I see the reasoning behind disabling bladeburner by default, but in BN6 and BN7 that should not be the case I think, so I run `autopilot.js --enable-bladeburner` there. 
After autopilot decides to install augs, the flag is lost and bladeburner gets disabled again - even when I already installed `The Blade's Simulacrum`. 

I think its more sensibe to default to run bladeburner regardless of the flag, at least when `The Blade's Simulacrum` is present. Even more better would be if this (and potentially all) autopilot flags would survive installing augs. (In this case, because the concurrent Bladeburner aug is pretty expensive and probably not obtained in the first resets). 

What do you think about this?

**Comment by Evanito** [comment]
Autopilot.js not maintaining arguments is a known missing feature at the moment, to my understanding 😅

**Comment by alainbryden** [comment]
Created #104 for this

**Comment by stedel** [comment]
That looks very promising 😄

**Comment by Evanito** [comment]
Now that #104 is closed, can we get a quick tutorial on how to use config files so we can close this? 😅

**Comment by alainbryden** [comment]
@Evanito  no need! It was always part of my plan to then leverage this feature to have autopilot automatically write out its config overrides to preserve them, so it should "just work" now.

**Comment by alainbryden** [comment]
@Evanito  That said, added docs here if you still want them for other scripts :)
https://github.com/alainbryden/bitburner-scripts/blob/main/README.md#config-files
