### ISSUE TITLE
Autopilot log confusing

### ISSUE THREAD

**Issue by zocke1r** [alainbryden/bitburner-scripts#103]
I find the log of the autopilot regarding the amount of augmentations one could currently install rather confusing:
Example:
Can afford: $133.922b for 7 levels of NeuroFlux and 5 of 31 accessible augmentations
Confusion:
This to me makes i sound like i can afford  a total 12 augments, 7 NeuroFlux and 5 other augments. But actually i can only afford 11 total augs, as 1 NeuroFlux is included in the 5 accessible, so to get the total number of augs i need to calculate 7 NF + 5 augs - 1 for NF being counted twice.
Possible Solution:
The easiest  solution would be to simply deduct 1 from the accessible augments assuming it includes a NF, similar to how the faction manager already does.

**Comment by alainbryden** [comment]
Fair point, I'll Mae the change
