### ISSUE TITLE
multiple issues

### ISSUE THREAD

**Issue by PrimalDerp** [alainbryden/bitburner-scripts#11]
welp here we go.

most of the scripts either run out of order or dont do their jobs.

multiple script are pulling ".txt" files that either dont exist or are always empty

if there is someone i missing here any help would be appreciated 

ns.read('/Temp/======.txt') somehow returned undefined or an empty string
is a prime example of the .txt files that im having issues with.

**Comment by alainbryden** [comment]
Most of these scripts will not do anything until you are late-game and have unlocked the many features they are trying to automate. The error messages can be ignored, the programs will shut themselves down if you don't have the necessary unlocks.

I suggest playing the game a little longer and then using scripts only as you need them. The daemon is designed so you can easily comment out the scripts you aren't ready for.

**Comment by alainbryden** [comment]
This is all fixed in the latest by the way. It was a common enough complaint that I had to do something about it :)
