### ISSUE TITLE
Casino doesn't always run to completion

### ISSUE THREAD

**Issue by alainbryden** [alainbryden/bitburner-scripts#112]
I noticed that the Casino doesn't always finish running. Not quite sure what does it but I should improve reliability somehow.

**Comment by Evanito** [comment]
![image](https://user-images.githubusercontent.com/5620666/166118070-3b7f0fe7-b56a-4216-8372-d95c332fda30.png)
Received this error today, not sure casino even started 😓

**Comment by alendaris** [comment]
Wondering if the script is just cycling faster than the engine can handle. I've had some weird pauses or extremely slow activity and it tends to make everything go tilt.

Looking at the bitburner source code, it looks like blackjack is dealing from a randomized standard deck of 52 cards, replacing and shuffling the cards when the deck is depleted. In theory, you might be able to use a card counting method or other advantage play scheme to reduce the natural house advantage and possibly reduce the frequency of save cycling (maybe only restore from a save if you've had loss of x% of your total at your last save).

**Comment by alainbryden** [comment]
https://github.com/alainbryden/bitburner-scripts/commit/0940d98ca033630f2f46030b5ae1319495e779e0
