### ISSUE TITLE
Autopilot.js: --disable-auto-destroy-bn doesn't work

### ISSUE THREAD

**Issue by Evanito** [alainbryden/bitburner-scripts#114]
Can't offer much more than the title, woke up in BN12 despite having the above flag enabled.

**Comment by alainbryden** [comment]
When was the last time you pulled the latest? Daemon didn't have a way to save its command line arguments until late last night.

**Comment by alainbryden** [comment]
Actually an even better way to tell is whether there's a file called "autopilot.js.config.txt" that contain your args in it. Only the latest does that.

**Comment by Evanito** [comment]
This was on commit d5b97d567466af371e90d206760a893b6bb2663c and yes that file exists.

**Comment by alainbryden** [comment]
Can you attach your game save?

**Comment by alainbryden** [comment]
Actually even before that, if you can paste the startup logs of your autopilot, that can confirm for me whether it's loading your config file.

**Comment by alainbryden** [comment]
Whoops, I see the bug now. No need for logs
