### ISSUE TITLE
helpers.js - formatDuration returned "2m 60s" during an autopilot countdown

### ISSUE THREAD

**Issue by alendaris** [alainbryden/bitburner-scripts#117]
The algorithm looks correct, so not sure what caused it.

https://github.com/alainbryden/bitburner-scripts/blob/082295e8620c9e5fd9e0e8bceab7344cfbab048f/helpers.js#L54-L79

**Comment by alainbryden** [comment]
It's just rounding. E.g. 59.9 seconds got rounded to 60

**Comment by alainbryden** [comment]
Probably just numeric imprecision, e.g. resulted in 2.9999999999987 when converted to hours, but the remainder is exactly 60 when converted to minutes.

**Comment by alainbryden** [comment]
Annoying and a bug for sure, bit not worth the trouble to handle all the edge cases.
