### ISSUE TITLE
Focus is being forced even with Neuroreceptor Management Implant

### ISSUE THREAD

**Issue by archraziel** [alainbryden/bitburner-scripts#12]
Even after purchasing Neuroreceptor Management Implant the work-for-factions scripts keeps focusing on the faction reputation work that is being worked on.

I tried to uncomment the lines:
487 ->         //if (await getNsDataThroughFile(ns, `ns.workForFaction('${factionName}', '${factionWork}') === true); ns.setFocus(${shouldFocusAtWork}`, '/Temp/work-for-faction.txt'))
522 - >         //if (!await getNsDataThroughFile(ns, `ns.workForFaction('${factionName}', '${work}') === true); ns.setFocus(${shouldFocusAtWork}`, '/Temp/work-for-faction.txt'))
650 ->          //if (await getNsDataThroughFile(ns, `ns.workForCompany('${companyName}')); ns.setFocus(${shouldFocusAtWork}`, '/Temp/work-for-company.txt')) {

It doesn't focus on the task but it keeps refreshing and sending me to terminal screen.
Am I missing something to make this work?

**Comment by alainbryden** [comment]
That code is from an old obsolete imementation of focus. You'll have to tweak the code yourself if you want it to manage your focus for you.

**Comment by archraziel** [comment]
To people that may come into this issue. For the focus to work you send the parameter in the ns.workForFaction to tell it to focus or not.

So, instead of this 
```
await getNsDataThroughFile(ns, ns.workForFaction('${factionName}', '${factionWork}') === true); ns.setFocus(${shouldFocusAtWork}, '/Temp/work-for-faction.txt')
```

It should be done like this
```
await getNsDataThroughFile(ns, `ns.workForFaction('${factionName}', '${work}',  ${shouldFocusAtWork})`, '/Temp/work-for-faction.txt')
```

**Comment by alainbryden** [comment]
Yeah I'm pretty slow getting around to fixing things that aren't impacting
my current run :p

**Comment by alainbryden** [comment]
Fixed, by the way
