### ISSUE TITLE
gang.js uses "Vigilante Justice" instead of "Ethical Hacking" for hack-based gangs

### ISSUE THREAD

**Issue by trambelus** [alainbryden/bitburner-scripts#120]
Using Ethical Hacking would yield better results for a hack-based gang, but the script doesn't have logic to detect or account for that yet.

**Comment by alainbryden** [comment]
Are you sure about that? In my tests, Vigilante Justice still performed better, so I got rid of code I used to have to toggle between the two.

If it was a bug that it was inferior, and it's since been fixed, I can put back some code to use the appropriate one for hack gangs.

**Comment by trambelus** [comment]
I did two quick tests in a mid- and a late-stage gang managed by gangs.js, and Ethical Hacking far outperforms Vigilante Justice. It probably has something to do with the script's prioritization of hacking skills over combat skills. Maybe at base stats, just after reset, Vigilante Justice is better?
