### ISSUE TITLE
Gang creation sequence throwing errors while attempting to pass arguments?

### ISSUE THREAD

**Issue by cullumar** [alainbryden/bitburner-scripts#122]
While at the very beginning of BN 12.9, I am running autopilot.js with no customizations or arguments after a git-pull.js refresh.

Shortly after kicking off, I receive the following error message which repeats every few seconds:

[10:12:04] WARN: (4 retries remaining): Error: Only strings, numbers, and booleans can be passed as arguments to other scripts.
/Temp/gang-createGang.js argument index 0 is of type object and value ["Speakers for the Dead","The Dark Army","The Syndicate","Tetrads","Slum Snakes","The Black Hand"]

Autopilot.js continues normal behavior, but the error continues to post to terminal and appears as "toasts" in the lower right.

Sorry to be bringing you issues today, Alain - appreciate your hard work and insight as always.

**Comment by cullumar** [comment]
This is the text of the toast:

WARNING: gangs.js Caught (and suppressed) an unexpected error while waiting to join a gang: Only strings, numbers, and booleans can be passed as arguments to other scripts. /Temp/gang-createGang.js argument index 0 is of type object and value ["Speakers for the Dead","The Dark Army","The Syndicate","Tetrads","Slum Snakes","The Black Hand"]

**Comment by Skyl3lazer** [comment]
Appears to be an issue with commit 2b8b2be972a5c9be7a29c3f5acc75ba09f57094

**Comment by cullumar** [comment]
The gang-related errors seem to end once a gang has been established - and gangs.js begins running and buying/upgrading gang members as normal.

However, this commit also has two other errors that keep popping up every 30 seconds or so - see attached.

Thanks!
![Capture](https://user-images.githubusercontent.com/73199155/166986728-6fb3b034-d4a3-4329-8ba5-8fae72b31612.PNG)
![Capture2](https://user-images.githubusercontent.com/73199155/166986729-5d18ae61-625c-424b-93b9-ddc00ce76a1d.PNG)

**Comment by cullumar** [comment]
These issues seem to have been resolved with the latest commits that fix git-pull.js and host-manager.js, so I'm marking this as closed for now - will open a new issue if the problem with gang creation persists.  Thanks Alain!

**Comment by alainbryden** [comment]
https://github.com/alainbryden/bitburner-scripts/commit/4dd390765fcd482f0e161a529b5a5c447ca85a19
