### ISSUE TITLE
gang.js tries creating gang before reaching karma -54k

### ISSUE THREAD

**Issue by schlaubi69** [alainbryden/bitburner-scripts#124]
Did a git-pull today and restartet autopilot. Now gang.js doesn't stop and wait for needed karma but tries to create a gang.
At the restart I was at about Karma -45k. Couldn't find the exact line in the script where it decides to wait or create a gang depdending on Karma. 

`WARNING: gangs.js Caught (and suppressed) an unexpected error while waiting to join a gang:
Only strings, numbers, and booleans can be passed as arguments to other scripts.
/Temp/gang-createGang.js argument index 0 is of type object and value ["Speakers for the Dead","The Dark Army","The Syndicate","Tetrads","Slum Snakes","The Black Hand"]

WARN: (4 retries remaining): Error: Only strings, numbers, and booleans can be passed as arguments to other scripts.
/Temp/gang-createGang.js argument index 0 is of type object and value ["Speakers for the Dead","The Dark Army","The Syndicate","Tetrads","Slum Snakes","The Black Hand"]

WARN: (3 retries remaining): Error: Only strings, numbers, and booleans can be passed as arguments to other scripts.
/Temp/gang-createGang.js argument index 0 is of type object and value ["Speakers for the Dead","The Dark Army","The Syndicate","Tetrads","Slum Snakes","The Black Hand"]

WARN: (2 retries remaining): Error: Only strings, numbers, and booleans can be passed as arguments to other scripts.
/Temp/gang-createGang.js argument index 0 is of type object and value ["Speakers for the Dead","The Dark Army","The Syndicate","Tetrads","Slum Snakes","The Black Hand"]

WARN: (1 retries remaining): Error: Only strings, numbers, and booleans can be passed as arguments to other scripts.
/Temp/gang-createGang.js argument index 0 is of type object and value ["Speakers for the Dead","The Dark Army","The Syndicate","Tetrads","Slum Snakes","The Black Hand"]

FAIL: (0 retries remaining): Error: Only strings, numbers, and booleans can be passed as arguments to other scripts.
/Temp/gang-createGang.js argument index 0 is of type object and value ["Speakers for the Dead","The Dark Army","The Syndicate","Tetrads","Slum Snakes","The Black Hand"]`

**Comment by schlaubi69** [comment]
It's line 102 in your last change  in commit "[Update some additional ram-dodging commands that don't use args](https://github.com/schlaubi69/Bitburner-scripts/commit/a2b8b2be972a5c9be7a29c3f5acc75ba09f57094)"
if I change it back to 
` await runCommand(ns, `${JSON.stringify(gangsByPower)}.forEach(g => ns.gang.createGang(g))`, '/Temp/gang-createGang.js');`
it works

**Comment by alainbryden** [comment]
https://github.com/alainbryden/bitburner-scripts/commit/4dd390765fcd482f0e161a529b5a5c447ca85a19
