### ISSUE TITLE
keep on getting error for stock scripts

### ISSUE THREAD

**Issue by reedM2** [alainbryden/bitburner-scripts#13]
Hi,

I just downloaded the latest version of your scripts and they work really well, but I keep on getting an error whenever I start daemon.js that says:

stats.js: FAIL: (0 retries remaining): ns.read('/Temp/stock-symbols.txt') somehow returned undefined or an empty string

which I think is also how I get a warning stating that stockmaster.js needs to be running for the stock probabilities file to be working.

I was just wondering if I may need to unlock something involving the stock in order for it to work or if it's something wrong with the coding itself.

Thanks

**Comment by alainbryden** [comment]
Hmm, yes you need access to the TSX api for that bit of stats to work. I'll
add a check to stop that warning from recurring, but yeah, it won't work
until you buy stock market api access.

**Comment by reedM2** [comment]
4S and TIX and 4STIX?

**Comment by alainbryden** [comment]
You don't need 4S, just the initial API access (5 billion in most BNs I
believe)

**Comment by reedM2** [comment]
oh ok, thanks
