### ISSUE TITLE
Faction Manager crashes when only your gang is joined

### ISSUE THREAD

**Issue by Mazorlion** [alainbryden/bitburner-scripts#131]
When only the gang is joined the most recent commit to faction-manager makes it crash. This is because the gang doesn't have `Neuroflux Governor` and it's assumed that _some_ faction will be able to supply it.

```
RUNTIME ERROR
faction-manager.js@home (PID - 213)
Args: ["-v"]

Cannot read properties of undefined (reading 'name')
stack:
TypeError: Cannot read properties of undefined (reading 'name')
at managePurchaseableAugs (home/faction-manager.js:660:80)
at async manageUnownedAugmentations (home/faction-manager.js:463:9)
at async Module.main (home/faction-manager.js:173:5)
```

The following image shows the stack trace of where it ends up returning undefined because it can't find a faction with the augment.

![image](https://user-images.githubusercontent.com/1725187/168178885-5bc58f70-7ba9-4e77-98ff-1dcbc260f3c8.png)

This maybe only realistically happens on earlyish installs in BN 2. I imagine otherwise you'll have at least a company faction joined or something by the time you get to the karma req for a gang in any other BN.

I considered sending a change but I wasn't sure exactly what your preference for handling it would be.

**Comment by alainbryden** [comment]
Thanks, just a bug in some refactoring I did. Case should be handled already.

**Comment by Mazorlion** [comment]
Thanks!
