### ISSUE TITLE
Memory problems after BN1.1 -> BN 4.1 -> BN1.2

### ISSUE THREAD

**Issue by RipperFox** [alainbryden/bitburner-scripts#136]
The helper scripts constantly run out of memory after I went the route in the subject.

Example:

`RUNTIME ERROR
faction-manager.js@home (PID - 1491)
Args: ["--verbose", "false"]

Run command returned no pid (command likely failed to run).
  Command: let result="";try{result=JSON.stringify(
            ns.getOwnedAugmentations(true)
        );}catch(err){result = "ERROR: " + (typeof err === 'string' ? err : err.message || JSON.stringify(err))}
        const f="/Temp/player-augs-purchased.txt"; if(ns.read(f)!==result) await ns.write(f,result,'w')
  Temp Script: /Temp/player-augs-purchased.txt.js
Ensure you have sufficient free RAM to run this temporary script.
stack:
autoRetry@home/helpers.js:290:51`

Also, progress at start of the new BN seems really slow - what could I do better?

**Comment by alainbryden** [comment]
This is expected behaviour. You'll see almost all SF4 scripts spit out a warning at start if you only have 4.1. I suggest you dont use them until youve upgraded home RAM to 256 and run daemon with  --reserve-ram 256, or flume out and do BN 4 2 more times.

**Comment by alainbryden** [comment]
For advice on what to do at the start of a new BN to speed things along I recommend discussing in the game Discord. I find autopilot.js takes care of it plenty fast, as long as you have enough SF4 levels.
