### ISSUE TITLE
couple of minor errors popping up, nothing big

### ISSUE THREAD

**Issue by reedM2** [alainbryden/bitburner-scripts#14]
Hi again,

So I see these 2 errors only once when I run the daemon script, probably nothing big but I just wanted to let you know

1.) RUNTIME ERROR
/Remote/weak-target.js@max-hardware
Args: ["n00dles", 1640755371142, 1640755422787, 51645, "Batch 1-weak2", 0, 0]
/Remote/weak-target.js cannot be run because it does not have a main function.

This appears randomly in the middle of the script run, doesn't stop anything but just pops up for some reason

2.) The file "/Temp/stock-probabilities.txt" is missing or empty. (Is stockmaster.js running?)

Just a warning from the stock script again, only shows up once when I start the script

**Comment by BasTijs** [comment]
Very nice work in this repo! Even works for a beginner if you disable several scripts (maybe make a -newbie flag? :D) Here is another warning related to server upgrades that happens often after deletion until all process are actually killed. Maybe actively kill them from the daemon?:
remove-worst-server.js: Deleted pserv which had only 16384 GB of RAM. 24 servers remain.
daemon.js: WARNING: Caught an error in the targeting loop: |DELIMITER|home|DELIMITER|daemon.js|DELIMITER|fileExists: Invalid hostname or IP: pserv<br><br>Stack:<br>daemon.js:L105@doesFileExist<br>daemon.js:L1433@isFlaggedForDeletion<br>daemon.js:L-1@unknown<br>daemon.js:L1438@buildServerList<br>daemon.js:L363@doTargetingLoop

**Comment by alainbryden** [comment]
Error 1 is a bug with the game itself, you should maybe post a comment on https://github.com/danielyxie/bitburner/issues/1714 to get it prioritized.

Warning 2 is a one-time thing, but yeah if it's annoying I can probably clean it up.
