### ISSUE TITLE
dus all this mean i dont have sifficient ram (sory if i am a nusins)

### ISSUE THREAD

**Issue by maxballz** [alainbryden/bitburner-scripts#140]
RUNTIME ERROR
/Tasks/ram-manager.js@home (PID - 255)
Args: ["--budget", 0.5, "--reserve", 0]

Run command returned no pid (command likely failed to run).
Command: let result="";try{result=JSON.stringify(
ns.getUpgradeHomeRamCost()
);}catch(err){result = "ERROR: " + (typeof err === 'string' ? err : err.message || JSON.stringify(err))}
const f="/Temp/getUpgradeHomeRamCost.txt"; if(ns.read(f)!==result) await ns.write(f,result,'w')
Temp Script: /Temp/getUpgradeHomeRamCost.txt.js
Ensure you have sufficient free RAM to run this temporary script.
stack:
Error: Run command returned no pid (command likely failed to run).
Command: let result="";try{result=JSON.stringify(
ns.getUpgradeHomeRamCost()
);}catch(err){result = "ERROR: " + (typeof err === 'string' ? err : err.message || JSON.stringify(err))}
const f="/Temp/getUpgradeHomeRamCost.txt"; if(ns.read(f)!==result) await ns.write(f,result,'w')
Temp Script: /Temp/getUpgradeHomeRamCost.txt.js
Ensure you have sufficient free RAM to run this temporary script.
at autoRetry (home/helpers.js:290:51)
at async runCommand_Custom (home/helpers.js:234:12)
at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
at async getNsDataThroughFile (home/helpers.js:137:12)
at async Module.main (home//Tasks/ram-manager.js:25:20)

**Comment by alainbryden** [comment]
You should join the discord and ask questions there, easier to provide troubleshooting help.
