### ISSUE TITLE
XP Mode issue

### ISSUE THREAD

**Issue by jdeitsch** [alainbryden/bitburner-scripts#142]
Running daemon in `-x` mode results in a constant pile of errors; the script still functions as intended, but it's incredibly noisy.

**Comment by alainbryden** [comment]
Can I get a screenshot of said errors?

**Comment by Evanito** [comment]
Is xp mode enabled by default on BN8 since hacking makes no money?

**Comment by alainbryden** [comment]
Bn8 sets the --silent-misfires flag so it can't be that.

**Comment by jdeitsch** [comment]
My apologies, I was on BN3.1, and I finished it before I got your response, since then I went for BN4.2 and now it's not occurring there; it was possibly a RAM issue.  Hopefully, getting SourceCode 4.2 and 4.3 will resolve it.
