### ISSUE TITLE
Error under BitBurner v1.7.0

### ISSUE THREAD

**Issue by rremo** [alainbryden/bitburner-scripts#144]
Thanks for your great script!

The following error message has recently appeared again and again and blocks the game
`RUNTIME ERROR
faction-manager.js@home (PID - 48)
Args: ["--verbose", "false"]

Run command returned no pid (command likely failed to run).
Command: let result="";try{result=JSON.stringify(
ns.getOwnedAugmentations(true)
);}catch(err){result = "ERROR: " + (typeof err === 'string' ? err : err.message || JSON.stringify(err))}
const f="/Temp/player-augs-purchased.txt"; if(ns.read(f)!==result) await ns.write(f,result,'w')
Temp Script: /Temp/player-augs-purchased.txt.js
Ensure you have sufficient free RAM to run this temporary script.
stack:
Error: Run command returned no pid (command likely failed to run).
Command: let result="";try{result=JSON.stringify(
ns.getOwnedAugmentations(true)
);}catch(err){result = "ERROR: " + (typeof err === 'string' ? err : err.message || JSON.stringify(err))}
const f="/Temp/player-augs-purchased.txt"; if(ns.read(f)!==result) await ns.write(f,result,'w')
Temp Script: /Temp/player-augs-purchased.txt.js
Ensure you have sufficient free RAM to run this temporary script.
at autoRetry (home/helpers.js:290:51)
at async runCommand_Custom (home/helpers.js:234:12)
at async getNsDataThroughFile_Custom (home/helpers.js:165:17)
at async getNsDataThroughFile (home/helpers.js:137:12)
at async Module.main (home/faction-manager.js:133:26)`

**Comment by alainbryden** [comment]
Hi, it sounds like you have recently unlocked Singularity, but did not unlock all 3 levels. This makes it very expensive to use.

You will want to start daemon.js with more --reserved-ram (1028 perhaps) and singularity scripts probably won't work until your home is at least that big.

Come to the Discord chat if you need more advice along these lines.
