### ISSUE TITLE
At least on BN3 there is only 75 favour needed to donate

### ISSUE THREAD

**Issue by schlaubi69** [alainbryden/bitburner-scripts#146]
Is there a possibility to check how much favour is needed for donating at factions? Or at least implement that only 75 are needed in BN3.

**Comment by alainbryden** [comment]
I already check for the actual favour to donate everywhere as far as I know. What makes you think it doesn't?

**Comment by schlaubi69** [comment]
I'm on BN3, there you need only 75 favour. The calculations of work-for-faction thus go up to needed rep for 150 Favour as a target for rep gain in a faction.
When the favour ist over 75 on reset, the Script Sees that I can donate and It's okay.

**Comment by alainbryden** [comment]
Check out this line 164 of the script:
```
    repToDonate = 150 * ((await tryGetBitNodeMultipliers(ns))?.RepToDonateToFaction || 1);
```
It already checks for this in the only way possible.

It seems that the problem you're having is that the "getBitnodeMultipliers" function is an intelligence (SF5) function, so until you complete BN5, there's no way to programatically determine the rep to donate.

You can manually edit that line for now in your situation, but you'll have to complete BN5 to unlock permanent access to that feature.

**Comment by schlaubi69** [comment]
OK, thank you. I'm on bitnode 9.2 now to get the home server RAM, then I go to BN5. Then BN8 for stock API.
