### ISSUE TITLE
Work-for-faction: grind rep for best faction after building a gang

### ISSUE THREAD

**Issue by schlaubi69** [alainbryden/bitburner-scripts#147]
After we build a gang we can purchase all augs from thiss faction and work-for-faction doesn't need to join and grind all other factions but could concentrate on the best one to grind rep for purchasing Neuroflux.

**Comment by alainbryden** [comment]
The script already does exactly this!

Did you know though that the gang doesn't provide you with all augmentations anymore? There are still some uniques you have ti grind for.

**Comment by schlaubi69** [comment]
Yes, I found that there are some unique ones.
The Script then only goes for factions with those unique augs?
It's a but Hard to Check even with this Information Label coming from the last update

**Comment by alainbryden** [comment]
The script only goes for factions with augs your gang doesn't provide if they are marked as **desired** augs (contribute to one of the configured desired stats).

You can check this by running "faction-manager.js", it outputs all desired augs with a * and lists the best/only faction you can buy these from.
