### ISSUE TITLE
Logic to steal 10b from the casino does not check that player has BN4

### ISSUE THREAD

**Issue by Nemithrell** [alainbryden/bitburner-scripts#159]
When starting autoPilot.js after installing augments before getting access to BN4.
It continously throws error that ns.stopAction() is not available without BN4 while trying to run /Temp/stop-action.txt.js

change to prevent this could example be to check for BN4 at start.
example:
change from:
async function maybeDoCasino(ns, player) {
	if (ranCasino) return;
	const casinoRanFileSet = ns.read(casinoFlagFile);

to:
async function maybeDoCasino(ns, player) {
	if (ranCasino) return;
	if (!(4 in unlockedSFs)) return;
	const casinoRanFileSet = ns.read(casinoFlagFile);

https://github.com/alainbryden/bitburner-scripts/blob/67a1584ceff06b5f0a7babd42b1f83a4bf7c16a5/autopilot.js#L403-L405

**Comment by alainbryden** [comment]
You don't actually need SF4 to do casino, that "StopAction" doesn't even really need to be in there, it's just a safety precaution.
