### ISSUE TITLE
/Remote/<script>.js cannot be run because it does not have a main function.

### ISSUE THREAD

**Issue by alainbryden** [alainbryden/bitburner-scripts#16]
I'm keeping this here as a placeholder for any who come here intending to report it.

![image](https://user-images.githubusercontent.com/2285037/147703073-882c8b45-b1f6-4305-9d0f-91f330be0c6d.png)

This is a bug with the game (bitburner) itself. There's an open issue in the bitburner backlog: https://github.com/danielyxie/bitburner/issues/1714

It happens because there is a race condition in the game code that will cause calls to ns.scp (or write) to not leave the file in a ready state for a short while after it's first copied / written. As such, when we first copy a script to a new remote server and try to run it, the run might fail that first time, but then work a subsequent time.

**Comment by alainbryden** [comment]
Still happens sometimes even with the workaround

**Comment by shinji257** [comment]
Just poking this closed issue to let you know I still get it from time to time.

**Comment by alainbryden** [comment]
Indeed, it's been a bit worse since I started RAM dodging school. Maybe just a longer sleep will do
