### ISSUE TITLE
Formatting of numbers (thousands separator, decimal symbol)

### ISSUE THREAD

**Issue by schlaubi69** [alainbryden/bitburner-scripts#161]
In helpers.js you create decimal numbers with decimal point and in other scripty you use toLocaleString(). I'm in german locale so my numbers will get a point as thousands seperator and usually there should be a comma for decimals.
So I get eg this line in Work for factions-Log:
_Doing 'hacking' work for "The Black Hand" until 175.000 rep. Currently at 96.939, earning 24.498 rep/sec. (ETA: 53m 6s)_

So the 175.000 look quite the same as the 24.498 which should be 24,498 in my locale.

As the game is generally in english perhaps it would be a good idea to set toLocaleString('en') to get consistent formatting. Or implement a decimal symbol according to the locale.

**Comment by alainbryden** [comment]
Thabks for https://github.com/alainbryden/bitburner-scripts/pull/162
