### ISSUE TITLE
`spend-hacknet-hashes.js` can be started multiple times

### ISSUE THREAD

**Issue by steven-r** [alainbryden/bitburner-scripts#163]
As for now, neither the script nor autostart checks if the script is running already. BB prevents to run the script with same parameters tiwce but you a eligible to run this script with different paramters as often as possible.

**Comment by steven-r** [comment]
Edit actually I planned to open this on my fork, but this seems to be a general problem with spend hacknet hashes

**Comment by alainbryden** [comment]
Its a feature! See the readme for more info
