### ISSUE TITLE
Faction Manager seems to believe I have about twice as much money as I do, and its making Ascend fail.

### ISSUE THREAD

**Issue by Thedakdragon** [alainbryden/bitburner-scripts#164]
As the comment posted, I went ahead and updated scritps to see if that would fix the problem, but it didn't make any difference
![FacMan](https://user-images.githubusercontent.com/75149134/171414881-4f6f6f49-7190-42e9-9b78-283191c1edff.jpg)
[bitburnerSave_1654089680_BN9x2.zip](https://github.com/alainbryden/bitburner-scripts/files/8814482/bitburnerSave_1654089680_BN9x2.zip)
.

**Comment by alainbryden** [comment]
Why did you close it? Did you figure out what happened?
