### ISSUE TITLE
Not Buying/Developing Darkweb Programs

### ISSUE THREAD

**Issue by Acheronx98** [alainbryden/bitburner-scripts#165]
Hello!

Recently (after one of the newer game updates) it seems that autopilot.js (or any of the other scripts like daemon.js, etc.) doesn't purchase the HTTPWorm.exe and SQLInject.exe programs, causing issues when trying to backdoor servers that require more than 3 ports open. 

I just tried a fresh pull of the repo and tried running autopilot, but I still had to connect to the darkweb and buy the programs after 30+ minutes (buy -a).

I've got BN 1.3, 4.3, 5.1, 8.2, and 9.2 (getting 8.3 now).

Please let me know if you need any logs and/or files to help.

**Comment by Acheronx98** [comment]
In daemon.js, like 277

`// Buy tor as soon as we can if we haven't already, and all the port crackers (exception: don't buy 2 most expensive port crackers until later if in a no-hack BN)`

Is there a way to disable this and have it run directly after the casino?

**Comment by alainbryden** [comment]
This was fixed a commit or two ago. You would have had this porblem with 8.1/2, but you won't have it with 8.3 once you get TRP

**Comment by alainbryden** [comment]
By the way, I won't disable the behaviour if not auto-buying the last 2 in a no hack bn, because it's just a waste of money. You can buy them manually of you want.
