### ISSUE TITLE
Stanek.js uses hardcoded awakeningRep and serenityRep numbers

### ISSUE THREAD

**Issue by dumpler** [alainbryden/bitburner-scripts#167]
During BN12.3 I ran into a problem that stanek.js stopped at 100m rep when 104m is needed. I complete it manualy.
![Снимок](https://user-images.githubusercontent.com/58024484/172920748-3ee9af8a-136c-4673-bb78-9bd2925d5fa2.JPG)

**Comment by alainbryden** [comment]
Good shout, at the time I was pretty sure nothing scaled augmentation rep requirements, not sure why - I was in BN12.20 at the time, I should have noticed.
