### ISSUE TITLE
Weird behaviors in BN8

### ISSUE THREAD

**Issue by ProjectYoung** [alainbryden/bitburner-scripts#168]
https://github.com/alainbryden/bitburner-scripts/blob/86ac0d146f0c5b64e7ce21564589f5cdd8265ac2/work-for-factions.js#L166
In BN8, I think the script will work for reputation to unlock donation, but the donation is unlocked at favor 0.
BTW, maybe we should not rely on donation as we don't earn money that quickly.

https://github.com/alainbryden/bitburner-scripts/blob/74c31ef81d21ecdc21ad30af2877e2b1589b6e6b/daemon.js#L274
The script almost never get to join BitRunners or Fulcrum because of lack of port tools.

**Comment by ProjectYoung** [comment]
And thank you! This script is amazingly powerful, I enjoyed reading it very much.

**Comment by McCloude** [comment]
The issue that I found when doing BN8 is that the following two scripts are not running.  I needed to manually run these to progress:

run Tasks/program-manager.js
run Tasks/backdoor-all-servers.js
