### ISSUE TITLE
work for factions doesn't use bitnode multipliers for earnFactionInvite() / getPlayerInfo()

### ISSUE THREAD

**Issue by EinzigeMeister** [alainbryden/bitburner-scripts#169]
When using player.hacking_mult or player.hacking_exp_mult (probably also any other multipliers) it pulls the base multiplier without the BN multiplier applied. This can cause long waits for joining factions when focusing on existing faction reputation / joining other factions should be the higher priority. Also, it displays the same uncorrected multiplier in the log, which was what first pointed me at this issue. This could also potentially be a BB issue, but haven't looked where to find/report them.
![Capture2](https://user-images.githubusercontent.com/106645041/174565740-b5c13f3c-4de6-4f52-bfe0-b674adb4c222.PNG)
![Capture](https://user-images.githubusercontent.com/106645041/174565742-57568e18-8b27-4b6a-9600-4a22de776c5c.PNG)

**Comment by Nopik** [comment]
+1 for this. I've just unlocked all other bitnodes and started farming BN12, this bug (and #167) makes things significantly slower. Early on it took <10 hours for BN12 to destroy, but after a while scripts stop Daedalus farming at 150 fav, hoping for donation after reboot. And, basically 15-30 minutes is lost easily on each unnecessary reboot. With 2 such reboots the whole BN destroy time can be like 10% longer than it should.

I also have some feeling that boosting Stanek on beginning will slow down the hacking significantly (not verified), which makes such quick unnecessary reboots even more painful.

**Comment by alainbryden** [comment]
@Nopik this issue doesn't affect rep to donate, which is handled correctly. You'll have to be more specific as to what your issue is. In late BN12, the rep required to donate is so high that TRP comes first.

**Comment by Nopik** [comment]
What I meant is that scripts stop working for Daedalus when it is enough to get 150 favour after reboot. But, on BN after reboot you need more than 150 fav to donate, so that causes unnecessary reboots, until Daedalus gets enough fav to unlock donates, then TRP can be obtained.

Although that might be separate bug, as somehow I misread the title and assumed that this bug is about the issue I described. Apparently this one is about invites instead, sorry for confusion.

**Comment by alainbryden** [comment]
I disagree that the script stops at 150 favour. The number 150 is not hard coded anywhere and it clearly gets the correct favour to donate number. Check out line 166 of the script where the correct number is determined, and lines 704 onwards where it's used. Whatever you're observing, I think you're misattributing it to favour to donate, which becomes impracticly high in BN12 as I mentioned.

**Comment by Nopik** [comment]
Hm, ok, thanks for pointing that out.
