### ISSUE TITLE
Autopilot Sleeve miscalculation

### ISSUE THREAD

**Issue by EinzigeMeister** [alainbryden/bitburner-scripts#171]
I came back to BN10 to get the last sleeve, and autopilot was sitting on 1Q and I noticed this message. It looks like it assumes you get an additional sleeve every time you play BN10, rather than just the first 3.
![Capture](https://user-images.githubusercontent.com/106645041/175834963-38bc14e8-8748-447d-9772-545ec9ac0fcd.PNG)

**Comment by alainbryden** [comment]
Aah good catch. Easy fix. Thanks

**Comment by EinzigeMeister** [comment]
Thanks! These scripts have been a huge help
