### ISSUE TITLE
Bladeburner gets activated even when --enable-bladeburner false is set for autopilot.js

### ISSUE THREAD

**Issue by schlaubi69** [alainbryden/bitburner-scripts#175]
The configuration inside of daemon.js to start bladeburner.js after bladeburners are availabe overrides the argument of autopilot.js not to enable bladeburner.
Found out as I try to get the SF6+ Achievement and have to disable bladeburner for this.

I think autopilot should give the argument disable-script bladeburner.js to daemon when enable-bladeburner is false

**Comment by schlaubi69** [comment]
added a pull request with a possible solution

**Comment by alainbryden** [comment]
The original intent was for '--enable-bladeburner' to actually kick it off, when set to true, not to disable and prevent it from running under normal conditions when it is set to 'false'. By default, bladeburner will be run by daemon.js if you're in a bladeburner bitnode, and this flag was never meant to disable that. If it were a `--disable-bladeburner' flag then, maybe, but I don't think it's too much to ask for people to edit code for special cases when they're going for an achievement (in this case, disable daemon from launching it, and even deleting the script to be on the safe side - which is what I did)

**Comment by schlaubi69** [comment]
Sorry, I quit playing so this wasn't in focus any more... I can understand your point, the only thing that irritated me was that there was this argumant and the script behaved other then the argument which said bladeburner would be deactivated.
But as you said on achievement hunt it's not too much for users to get active themselves. At least it is still a coding game and not only a "find the script in the net" game.
