### ISSUE TITLE
Casino script resets if total earning this session is 0

### ISSUE THREAD

**Issue by kotenok2000** [alainbryden/bitburner-scripts#180]
Casino script resets if won amount is 0.  Casino should reset only if total earning this session is less than 0.

**Comment by alainbryden** [comment]
Casino script never resets, it just reloads the page without saving. It does this after every loss, which is optimal.

**Comment by kotenok2000** [comment]
Yes. I meant reloads. But can zero winnings be considered loss?

**Comment by alainbryden** [comment]
The game script doesn't reload if you get a "Push" result (tie) on a hand,
but absolutely if you win a hand (save) and then lose a hand and are now
back to zero, it's far better to reload (go back to being in the green)
than keep playing with a loss.
