### ISSUE TITLE
update autopilot.js

### ISSUE THREAD

**Issue by otto-kirchheim** [alainbryden/bitburner-scripts#186]
In BN8: after start or after reset $250 million in starter funds (200ms since last reset), is more than 5b/min, and skips ranCasino 

autopilot.js row 426 : `if (player.money / player.playtimeSinceLastAug > 5e9 / 60000)`

`if (player.money / player.playtimeSinceLastAug > 5e9 / 60000 && !player.bitNodeN == 8)`

#185

**Comment by alainbryden** [comment]
Gah, I thought this would happen
