### ISSUE TITLE
Will you update scripts for 2.0.1?

### ISSUE THREAD

**Issue by kotenok2000** [alainbryden/bitburner-scripts#192]
[V2_0_0_API_BREAK.txt](https://github.com/alainbryden/bitburner-scripts/files/9364117/V2_0_0_API_BREAK.txt)

**Comment by alainbryden** [comment]
Yes, see #184

**Comment by notacompletemoron** [comment]
Lines 466 and 467 in "work-for-faction.js" can be updated as such:

            return ns.print(`Your combination of Hacking mult (${formatNumberShort(player.mults.hacking)}), exp_mult ` +
                `(${formatNumberShort(player.mults.hacking_exp)}), and bitnode hacking / study exp mults ` +

**Comment by notacompletemoron** [comment]
All skills have been reconfigured from "player.strength" to "player.skills.strength" for example.

**Comment by notacompletemoron** [comment]
getFactionReputation has been changed to getFactionRep

**Comment by alainbryden** [comment]
@notacompletemoron All of the issues you mentioned should now be resolved.

**Comment by alainbryden** [comment]
I think this is mostly taken care of now, let's just open up new tickets for each individual discovered issue from here on.
