### ISSUE TITLE
Subfolder option breaks script

### ISSUE THREAD

**Issue by doug-w** [alainbryden/bitburner-scripts#20]
The only use of subfolder in git-pull.js is line 29:
const remoteFilePath = baseUrl + localFilePath.substr(options.subfolder.length);

This simply strips part of the file to get causing all files to fail to download IE:
WARNING: "analyze-hack.js" was not updated. (Currently running or not located at https://raw.githubusercontent.com/alainbryden/bitburner-scripts/main/yze-hack.js )

when options.subfolder = "test";

**Comment by alainbryden** [comment]
Ah, never actually tested the subfolder

**Comment by pabluuz** [comment]
Use 
`subfolder = "/test"`
instead of 
`subfolder = "test"`

Bug still exists, but it's easy to walk around it
