### ISSUE TITLE
Issue with hack|weak|grow Tasks

### ISSUE THREAD

**Issue by Maskmaker-JLo** [alainbryden/bitburner-scripts#212]
Hi,

since update the main hacking tasks seems to work not prperly. When starting autopilot.js follwing error message appears after a few minutes:

`WARNING: autopilot.js Caught (and suppressed) an unexpected error:
|DELIMITER|home|DELIMITER|autopilot.js|DELIMITER|run: 'args' is not an array of script args` 

Is there any change how to use the autopilot?

Kind regards

JLo

**Comment by alainbryden** [comment]
Will be addressed in #192
