### ISSUE TITLE
APIV2: ns.singularity.getCurrentWork()

### ISSUE THREAD

**Issue by alainbryden** [alainbryden/bitburner-scripts#222]
There are a places in daemon.js (for exp sharing) and sleeve.js (for following player) that rely on the old `.isWorking` property of the player object that is now removed. These won't work until we add a call to `getCurrentWork()`

**Comment by storyd** [comment]
https://github.com/alainbryden/bitburner-scripts/blob/main/daemon.js#L727

https://github.com/alainbryden/bitburner-scripts/blob/main/sleeve.js#L186
https://github.com/alainbryden/bitburner-scripts/blob/main/sleeve.js#L194
