### ISSUE TITLE
Turning on verbose to troubleshoot getNsDataThroughFile

### ISSUE THREAD

**Issue by xtrapwr** [alainbryden/bitburner-scripts#223]
When I add a true argument to getNsDataThroughFile to enable verbose mode for troubleshooting, I'm getting a runtime error. 

RUNTIME ERROR
/Temp/sleeve-setToBladeburnerAction.txt.js@home (PID - 59459)
Args: [0, "Infiltrate synthoids", ""]

The keyword 'let' is reserved (1:52) (sorry we can't be more helpful)

It appears to be caused by the verbose output wrapper in helper.js 225:39.  Specifically I'm trying to troubleshoot strange sleeve behavior, and adding the logging on sleeve.js 240 will trigger the run time error when attempting to execute the logging enabled 
/Temp/sleeve-setToBladeburnerAction.txt.js   I expected the below warning, because a logging enabled script should generate a new command file.

sleeve.js: WARNING: Had to overwrite temp script /Temp/sleeve-setToBladeburnerAction.txt.js
Old Contents:
export async function main(ns) { let r;try{r=JSON.stringify(
    ns.sleeve.setToBladeburnerAction(ns.args[0], ns.args[1], ns.args[2])
);}catch(e){r="ERROR: "+(typeof e=='string'?e:e.message||JSON.stringify(e));}
const f="/Temp/sleeve-setToBladeburnerAction.txt"; if(ns.read(f)!==r) await ns.write(f,r,'w') }
New Contents:
export async function main(ns) { try { let output = let r;try{r=JSON.stringify(
    ns.sleeve.setToBladeburnerAction(ns.args[0], ns.args[1], ns.args[2])
);}catch(e){r="ERROR: "+(typeof e=='string'?e:e.message||JSON.stringify(e));}
const f="/Temp/sleeve-setToBladeburnerAction.txt"; if(ns.read(f)!==r) await ns.write(f,r,'w'); ns.tprint(JSON.stringify(output)); } catch(e) { ns.tprint('ERROR: '+(typeof e=='string'?e:e.message||JSON.stringify(e))); throw(e); } }
This warning is generated as part of an effort to switch over to using only 'immutable' temp scripts. Please paste a screenshot in Discord at https://discord.com/channels/415207508303544321/935667531111342200

**Comment by alainbryden** [comment]
Fixed, thanks for hunting down the root cause
