### ISSUE TITLE
Sleeves are not validating job assignment

### ISSUE THREAD

**Issue by xtrapwr** [alainbryden/bitburner-scripts#226]
I'm not yet sure if this is a known v2 bug, but it's currently possible for your scripts to assign a sleeve a task using the ram dodge, but the sleeve doesn't actually switch tasks, and your script has no way of confirming that because the ram dodge returned a true even though the sleeve assignment failed. 

I'm still trying to hunt down the root cause, but putting this out here if anyone else wants to help with the digging.

I added some basic logging to confirm the issue.

Here is sleeve.js trying to assign a sleeve a task:

INFO: Using a temporary script (/Temp/sleeve-setToBladeburnerAction.txt.js) to execute the command:
  let r;try{r=JSON.stringify(
    ns.sleeve.setToBladeburnerAction(ns.args[0], ns.args[1], ns.args[2])
);}catch(e){r="ERROR: "+(typeof e=='string'?e:e.message||JSON.stringify(e));}
const f="/Temp/sleeve-setToBladeburnerAction.txt"; if(ns.read(f)!==r) await ns.write(f,r,'w')
With the following arguments:    [6,"Field Analysis",""]

Process 139 is done. Reading the contents of /Temp/sleeve-setToBladeburnerAction.txt...

Read the following data for command ns.sleeve.setToBladeburnerAction(ns.args[0], ns.args[1], ns.args[2]):
true    <-- ram dodge getNsDataThroughFile() returns true

SUCCESS: Set sleeve 6 to Bladeburner Field Analysis  

LOG: But Sleeve is actually doing RECOVERY <-- live check of ns.sleeve.getTask(i).type shows task did not change.

INFO: Sleeve 6 is doing Field Analysis in Bladeburner.

**Comment by alainbryden** [comment]
Indeed, there appears to be a game bug that incorrectly returns "true" for all bladeburner actions, even if they've failed.

That said, I think I also have a bug here that's resulting in the task not being set correctly (perhaps "Field Analysis" is not the correct string). I'll dig into the code and see.

**Comment by xtrapwr** [comment]
I stumbled upon this when I realized the script struggled to assign any job to sleeve 6, and only sleeve 6.  There is definitely weirdness going on with sleeves in general in v2.

**Comment by alainbryden** [comment]
Figured this out - the game now expects lower-case "a" "Field analysis" rather than "Field Analysis" - the code that tests this is currently very strict and case-sensitive.

Doesn't fix the overall validation of job assignments, but I think I'll just wait on the game to fix that rather than add a workaround.
