### ISSUE TITLE
about args of daemon.js of init-max-target and looping-mode

### ISSUE THREAD

**Issue by lucknum24** [alainbryden/bitburner-scripts#228]
If I set looping mode, the init-max-target would be invalid.
I check daemon.js at row 262. If dont disable stockmode, the stockFocus will be true. Then at 347, the maxTargets will not use my setting.
My question is how to set init max target in looping mode with stock mode.
Thanks.

**Comment by alainbryden** [comment]
Fair point. Fixed.
