### ISSUE TITLE
autopilot.js: mainloop stocksvalue not set to getStocksValue

### ISSUE THREAD

**Issue by otto-kirchheim** [alainbryden/bitburner-scripts#229]
autopilot.js - mainloop 
row 155: `try { stocksValue = await getStocksValue(ns); } catch { /* Assume if this fails (insufficient ram) we also have no stocks */ }`

**Comment by alainbryden** [comment]
Code looks fine to me. What's the problem?

**Comment by otto-kirchheim** [comment]
"stocksValue" is set to 0 and after "getStocksValue", is still 0.
but the value is required for "manageReservedMoney" and "checkOnDaedalusStatus".

Incidentally, "checkOnDaedalusStatus" is only called once at startup, regardless of whether Daedalus is available or not

**Comment by davidakachaos** [comment]
The code Otto shared the code that should be there in autopilot.js, but at a quick glance the code there is:
```
let stocksValue = 0;
try { await getStocksValue(ns); } catch { /* Assume if this fails (insufficient ram) we also have no stocks */ }
```
So the value never gets set currently.

**Comment by alainbryden** [comment]
Ooh jeeze. Okay, thanks for translating!
