### ISSUE TITLE
Is there an option to disable casino script?

### ISSUE THREAD

**Issue by kotenok2000** [alainbryden/bitburner-scripts#230]

**Comment by davidakachaos** [comment]
No, but you can edit autopilot.js to disable it.

Why would you disable it?

**Comment by kotenok2000** [comment]
I believe in some cases sleeves earn a lot more money than casino.


06.09.2022 08:26:37, David Westerink пишет:

**Comment by alainbryden** [comment]
This case is supposed to be handled already. Autopilot detects if in the
first minute if the BN you are earning money fast enough for casino to be
unnecessary, and skips it for that reset.

**Comment by alainbryden** [comment]
Added an explicit option to disable the casino completely in #248
