### ISSUE TITLE
Casino restarting game

### ISSUE THREAD

**Issue by galaxine-senpai** [alainbryden/bitburner-scripts#231]
For some reason each time casino is ran, the game restarts. Is there any way to fix this?

**Comment by galaxine-senpai** [comment]
Solved by setting wait time in `autopilot.js` to 10 seconds (10000)

**Comment by galaxine-senpai** [comment]
10 seconds wasn't enough, I would presume it has to do with the casino script it's self.

**Comment by alainbryden** [comment]
As designed. There's a section on casino.js in the readme if you want to know why.
