### ISSUE TITLE
Developement build on steam

### ISSUE THREAD

**Issue by gobba** [alainbryden/bitburner-scripts#232]
Just a heads up that I tried the devbuild on steam and it breaks the ran-casino function. It cant write bool to file, ns.write needs a string instead. Easy fix :

`await ns.write(ran_flag, "true", "w");`
where applicable.

Dont know if or when the dev build will be released. 

Really enjoy your scripts!

**Comment by alainbryden** [comment]
Thanks for the heads up! I'll switch to dev and fix things asap, since
it'll be backwards compatible with prod

**Comment by alainbryden** [comment]
Looks like that's going to be the only spot that's a problem. Typical ram-dodging scripts that write results to file (often a true/false result) use `JSON.stringify` on the value before they write it, which takes care of the issue.

Thanks again!
