### ISSUE TITLE
Consider Having sleeve.js Prioritize Shock Recovery

### ISSUE THREAD

**Issue by userX-324-A** [alainbryden/bitburner-scripts#233]
I'm playing post 10.3 where I have 8 sleeves. I found that they were taking a long time recovering from shock and prioritized committing crimes. 

I changed line https://github.com/alainbryden/bitburner-scripts/blob/main/sleeve.js#L189 from this: 
<code>
    if (sleeve.shock > options['min-shock-recovery'] || sleeve.shock > 0 && options['shock-recovery'] > 0 && Math.random() < options['shock-recovery'])
</code>

to this: 
<code>
    if (sleeve.shock > options['min-shock-recovery'] || sleeve.shock > 0 && options['shock-recovery'] > 0 && Math.random() < options['shock-recovery'] || sleeve.shock > 0 && ns.heart.break() <= -54000)
</code>

and I believe I get better results in completing bitnodes. Before this change I ran 11.1 in around 48 hours. After I ran 11.3 in roughly 36 hours. This isn't a fair comparison, I admit. But maybe this is worth a look. 

Thanks for considering.

**Comment by alainbryden** [comment]
There is an option to do force full recovery (--shock-recovery 1) but
you're probably right that it should be prioritized if there's nothing
"better" to do. I'll insert further shock recovery as the final priority
before doing crime.
