### ISSUE TITLE
Ascend.js will break if it cant run purchase4SMarketDataTixApi due no access

### ISSUE THREAD

**Issue by teunisv** [alainbryden/bitburner-scripts#243]
https://github.com/alainbryden/bitburner-scripts/blob/d16d611546dc9da24d71351deaea18a516349d3b/ascend.js#L124

My work around: (there probally a better way.)
```
    let have4sApi = await getNsDataThroughFile(ns, `ns.stock.has4SDataTIXAPI()`, `/Temp/stock-has4SDataTIXAPI.txt`);
    if(have4sApi) { 
        await getNsDataThroughFile(ns, 'ns.stock.purchase4SMarketDataTixApi()', '/Temp/stock-purchase4SMarketDataTixApi.txt');
    }
```
if it happens again i'll post the error message that appeared in /Temp/stock-purchase4SMarketDataTixApi.txt

**Comment by alainbryden** [comment]
Valid fix - thanks for the heads up.
