### ISSUE TITLE
autopilot sleeve check logic error?

### ISSUE THREAD

**Issue by srhuston** [alainbryden/bitburner-scripts#247]
I think there's a bug in autopilot.js line 231:
`		const shouldHaveSleeveCount = Math.min(8, 6 + dictOwnedSourceFiles[10]);
`

I believe it should be this:
`		const shouldHaveSleeveCount = Math.min(8, 6 + (dictOwnedSourceFiles[10] || 0));
`

That would match similar to line 217.  I'm not a JS programmer, so I may have syntax wrong, but I know various other languages and I believe line 217 is protecting against the case where dictOwnedSourceFiles doesn't return at all and so the `|| 0` would return zero (which then gets +1 to report that the current BN was destroyed).  I think 231 is wrong because I went through BN10 and this never triggered to stop the script from autocompleting it, so it moved on to BN2 without suggesting I load up on sleeves.  On the other hand waiting for the return to destroy 10.2 later could be seen as a proper thing to do, but I suspect there was an error in the code when it tried to execute this line and it continued on to destroy the node.  Since all output isn't logged, and I wasn't watching when it happened, I don't know for sure - and I'm not starting a whole new game to get to that point and wait for it right now :D

**Comment by alainbryden** [comment]
That makes sense. Feel free to submit a pull request to that effect.
