### ISSUE TITLE
Stockmaster doesn't keep up with available cash

### ISSUE THREAD

**Issue by doug-w** [alainbryden/bitburner-scripts#25]
While running on bn2 to get the 25t to get the last augment, I notice that around 3t of stock it doesn't seem to keep up with the available cash IE at the moment it looks like:
Money | $23.582t |  
Stock | $3.418t

**Comment by JoshIce** [comment]
It shouldn't necessarily use all the allowed cash available since it only invests in stocks that are projected to grow by a certain amount. I'll try to see if I can reproduce your issue, but I'm sure I've seen it invest more than 3t before.

**Comment by alainbryden** [comment]
Also keep in mind that there's a maximum amount of each stock you can buy.
Sounds like you're hitting that max, especially if you dont have shorting
unlocked.

**Comment by alainbryden** [comment]
If you have the stockmaster summary tail window open and full screen, it'll probably show that you have the maximum amount in all long positions. The buy logs also says (max) when you've bought the maximum shares arable for a stock.
