### ISSUE TITLE
String Split in helpers.js is not a valid function after V2.2 update

### ISSUE THREAD

**Issue by ashugar** [alainbryden/bitburner-scripts#251]
Code line 82:
`export function hashCode(s) { return s.split("").reduce(function (a, b) { a = ((a << 5) - a) + b.charCodeAt(0); return a & a }, 0); }`

Error stack:
`RUNTIME ERROR
stats.js@home (PID - 5139)

s.split is not a function
stack:
TypeError: s.split is not a function
    at hashCode (home/helpers.js:82:40)
    at getNsDataThroughFile_Custom (home/helpers.js:152:25)
    at getNsDataThroughFile (home/helpers.js:138:18)
    at getAllServersInfo (home/stats.js:198:18)
    at async Module.main (home/stats.js:129:33)
    at async M (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:271496)`

I'm unable to fix this particular problem after the V2.2 update.

Additional info:
the hashCode function is called via various other scripts and has a particular problem when hashing out commands.

i.e.:
`return await getNsDataThroughFile(ns, 'ns.args.map(ns.getServer)', '/Temp/getServers.txt', serverNames);`
The part `ns.arge.map(ns.getServer)` is calling a command inside a command. But, per the V2.2 Update, we cannot nest commands like this.  The issue then becomes how to properly pass this onto the function and for it to get properly hashed. Not sure if this is the job of the helper, or a rewrite of the function to pass this along in a different manner.

P.S. I'm not vocabulary savvy here, so I hope I'm at least getting the idea across.

**Comment by ashugar** [comment]
Fixes for run binding issues in helper.js.

1. Change in getNsDataThroughFile function
    `const run = ns.run.bind(ns); // V2.2 Update`
    `return await getNsDataThroughFile_Custom(ns, run, command, fName, args, verbose, maxRetries, retryDelayMs);`

2. Change in runCommand function
`const run = ns.run.bind(ns); // V2.2 Update`
`return await runCommand_Custom(ns, run, command, fileName, args, verbose, maxRetries, retryDelayMs);`

I'll add more as I figure them out, specifically for this file, since I already have this thread up and going.

**Comment by alainbryden** [comment]
string.split is always a valid function. It's provided by javascript, not the game.

This error message is a red-herring, likely some other API break, or a change you made to try and fix an API break caused this function to be passed `undefined` rather than a valid string.

Nevertheless, this ticket is now obsolete since the game reverted the API breaks regarding requiring `bind`.
