### ISSUE TITLE
2.2.0 analyze-hack.js

### ISSUE THREAD

**Issue by dracomalar93** [alainbryden/bitburner-scripts#252]
Here is a fix for analyze-hack.js:

On Line 44, change from:
`var servers = serverNames.map(ns.getServer);`

To:
```
const getServer = ns.getServer.bind(ns); // v2.2.0
var servers = serverNames.map(getServer);
```

On analyze-hack.js, it was giving this error:

RUNTIME ERROR
analyze-hack.js@home (PID - 766)

ns.getServer called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const getServer = ns.getServer.bind(ns);
getServer("home",0,["home","daemon-4","daemon-3","daemon-2","daemon-1","daemon-0","daemon","daemon-23","daemon-22","daemon-21","daemon-20","daemon-19","daemon-18","daemon-17","daemon-16","daemon-15","daemon-14","daemon-13","daemon-12","daemon-11","daemon-10","daemon-9","daemon-8","daemon-7","daemon-6","daemon-5","darkweb","iron-gym","nectar-net","phantasy","the-hub","catalyst","lexo-corp","summit-uni","aevum-police","snap-fitness","harakiri-sushi","max-hardware","neo-net","netlink","I.I.I.I","hong-fang-tea","zer0","silver-helix","johnson-ortho","computek","joesguns","sigma-cosmetics","foodnstuff","CSEC","omega-net","avmnite-02h","syscore","millenium-fitness","rho-construction","zb-institute","alpha-ent","global-pharm","aerocorp","deltaone","zeus-med","icarus","defcomm","taiyang-digital","applied-energetics","stormtech","kuai-gong","omnitek","clarkinc","blade","b-and-a","megacorp","ecorp","galactic-cyber","unitalife","solaris","nova-med","titan-labs","vitalife","4sigma","infocomm","microdyne","fulcrumtech",".","powerhouse-fitness","fulcrumassets","nwo","The-Cave","univ-energy","zb-def","run4theh111z","helios","omnia","rothman-uni","crush-fitness","n00dles"]);

stack:
Error: 
ns.getServer called with no this value.
ns functions must be bound to ns if placed in a new
variable. e.g.

const getServer = ns.getServer.bind(ns);
getServer("home",0,["home","daemon-4","daemon-3","daemon-2","daemon-1","daemon-0","daemon","daemon-23","daemon-22","daemon-21","daemon-20","daemon-19","daemon-18","daemon-17","daemon-16","daemon-15","daemon-14","daemon-13","daemon-12","daemon-11","daemon-10","daemon-9","daemon-8","daemon-7","daemon-6","daemon-5","darkweb","iron-gym","nectar-net","phantasy","the-hub","catalyst","lexo-corp","summit-uni","aevum-police","snap-fitness","harakiri-sushi","max-hardware","neo-net","netlink","I.I.I.I","hong-fang-tea","zer0","silver-helix","johnson-ortho","computek","joesguns","sigma-cosmetics","foodnstuff","CSEC","omega-net","avmnite-02h","syscore","millenium-fitness","rho-construction","zb-institute","alpha-ent","global-pharm","aerocorp","deltaone","zeus-med","icarus","defcomm","taiyang-digital","applied-energetics","stormtech","kuai-gong","omnitek","clarkinc","blade","b-and-a","megacorp","ecorp","galactic-cyber","unitalife","solaris","nova-med","titan-labs","vitalife","4sigma","infocomm","microdyne","fulcrumtech",".","powerhouse-fitness","fulcrumassets","nwo","The-Cave","univ-energy","zb-def","run4theh111z","helios","omnia","rothman-uni","crush-fitness","n00dles"]);

**Comment by ashugar** [comment]
I made a slightly different change and it seems to work. Maybe this is a better solution than binding to a variable?
`var servers = serverNames.map(ns.getServer.bind(ns));`
I'm thinking it was viable simply because it wasn't calling anything else inside the command.

**Comment by dracomalar93** [comment]
I see. Thank you for that update
