### ISSUE TITLE
backdooring success messaged printed several times for a single server

### ISSUE THREAD

**Issue by steven-r** [alainbryden/bitburner-scripts#256]
Env: 2.2.0 (Steam)

Backdooring servers might take some time and therefore the script to backdoor a single server is run more than once.

This results in several messages showing the success of a backdoor operation.

**Comment by alainbryden** [comment]
The master script that kicks off the "background" backdoor scripts
shouldn't be running frequently enough for this to happen.

In what circumstances does it run multiple times?

**Comment by steven-r** [comment]
see a screenshot right now:

![image](https://user-images.githubusercontent.com/4533301/210673788-d9f0ff9c-2ac1-48f8-ab4a-e353a06c2bd8.png)

backdoor takes more than 30 secs.
You will see that netlink and computek are there twice, after I've disabled the patch.

**Comment by steven-r** [comment]
BTW: This is not related to the backdoor scripts:
```
(PID - 12) /Remote/grow-target.js alpha-ent 1672877846713 1672877846713 0 prep 0 0
(PID - 13) /Remote/grow-target.js alpha-ent 1672877846713 1672877846713 0 prep 0 0
```

**Comment by steven-r** [comment]
According to discord this is a bug in BB (introduced by https://github.com/bitburner-official/bitburner-src/pull/296).

I would suggest to close this issue or keep it as an enhancement to reduce `ns.run` executions that will be fail out due to this.

**Comment by alainbryden** [comment]
Despite the behaviour being triggered by a regression in the game, I still think it's valid to check in advance.

I was initially worried about the new inclusion of `ns.ps` adding to the RAM overhead of the script, but it's only 0.2 GB in a script that's already 5GB (clearly hasn't been ram optimized) , so I don't think I have to worry about it.

**Comment by Mughur** [comment]
> According to discord this is a bug in BB (introduced by [bitburner-official/bitburner-src#296](https://github.com/bitburner-official/bitburner-src/pull/296)).

no,  [#260](https://github.com/bitburner-official/bitburner-src/pull/260) caused the bug, [https://github.com/bitburner-official/bitburner-src/pull/296] fixes it
