### ISSUE TITLE
Issue with Autopilot and NFs

### ISSUE THREAD

**Issue by gbreeden01** [alainbryden/bitburner-scripts#264]
I've been having an issue where the Autopilot.js script seems to be ignoring the "only count NFs as one"; in early game on a bitnode, it will hack Tian Di Hui, but keep resetting well before the 75k, buying a bunch of NFs; this continues until it can't afford them any more.

I'm on BitNode 9.2, and think it's reset 3-4 times already on this run.

FYI - I thought it was worth mentioning.

**Comment by alainbryden** [comment]
What options did you actually put in your config? Sounds like you have
inadvertently asked it to reset as soon as it can afford 1 additional level
of NF. It might be a bug, but it could also be a misunderstanding of how
the arguments are intended to be used.

**Comment by gbreeden01** [comment]
I'm actually using the default settings "run autopilot.js" vanilla-ly. I even updated all of the scripts to confirm today, as I saw there were various updates over the past few days. 

The settings in autopilot.js are: 
['install-at-aug-count', 11], // Automatically install when we can afford this many new augmentations (with NF only counting as 1)
['install-at-aug-plus-nf-count', 14], // or... automatically install when we can afford this many augmentations including additional levels of Neuroflux

**Comment by alainbryden** [comment]
That's fine then.

Can you show me the log suggesting it's installing for fewer than 11 augs
or 14 levels of NF?

You should be able to get a history from your persistent lof file. I
believe it's called "log.autopilot.txt"

**Comment by gbreeden01** [comment]
Sure - 

Here are the first 6 installs after my 5.1 completion: 
2023-01-02T22:38:26 BN 5.1 completed at 40h 49m 33s (hack (4500) win condition)
2023-01-03T05:09:00 Invoking ascend.js at 6h 30m 23s  since last aug to install: 10 of 91 remaining augmentations + 3 levels of NeuroFlux.
  Augs: ["Speech Processor Implant", "Hacknet Node Kernel Direct-Neural Interface", "Social Negotiation Assistant (S.N.A)", "Nuoptimal Nootropic Injector Implant", "ADR-V1 Pheromone Gene", "Speech Enhancement", "Hacknet Node CPU Architecture Neural-Upload", "Hacknet Node Cache Architecture Neural-Upload", "Hacknet Node NIC Architecture Neural-Upload", "Neurotrainer I", "NeuroFlux Governor"]
2023-01-03T13:14:16 Invoking ascend.js at 8h 5m 6s    since last aug to install: 4 of 81 remaining augmentations + 9 levels of NeuroFlux.
  Augs: ["Cranial Signal Processors - Gen I", "Hacknet Node Core Direct-Neural Interface", "BitWire", "Synaptic Enhancement Implant", "NeuroFlux Governor"]
2023-01-03T23:35:01 Invoking ascend.js at 10h 20m 32s since last aug to install: 2 of 77 remaining augmentations + 10 levels of NeuroFlux.
  Augs: ["Neuralstimulator", "Neuroreceptor Management Implant", "NeuroFlux Governor"]
2023-01-04T10:30:09 Invoking ascend.js at 10h 54m 57s since last aug to install: 8 of 75 remaining augmentations + 1 levels of NeuroFlux.
  Augs: ["PCMatrix", "Cranial Signal Processors - Gen II", "Cranial Signal Processors - Gen III", "Neural-Retention Enhancement", "Embedded Netburner Module", "CRTX42-AA Gene Modification", "Artificial Synaptic Potentiation", "Neurotrainer II", "NeuroFlux Governor"]
2023-01-04T22:35:21 Invoking ascend.js at 12h 5m 2s   since last aug to install: 4 of 66 remaining augmentations + 7 levels of NeuroFlux.
  Augs: ["DataJack", "Power Recirculation Core", "LuminCloaking-V1 Skin Implant", "NeuroFlux Governor", "LuminCloaking-V2 Skin Implant"]
2023-01-05T14:40:34 Invoking ascend.js at 16h 5m 2s   since last aug to install: 2 of 62 remaining augmentations + 7 levels of NeuroFlux.
  Augs: ["Neuregen Gene Modification", "SmartSonar Implant", "NeuroFlux Governor"]

**Comment by gbreeden01** [comment]
Here's what happened today - note when it kept trying to reset early, I killed autopilot and forced it to finish out a good augment install; and then 6 hours later it did it again (3 augs and 10 levels of NF):

2023-01-09T02:10:57 BN 9.1 completed at 147h 30m 9s (hack (6000) win condition)
2023-01-09T07:01:45 Invoking ascend.js at 4h 50m 35s  since last aug to install: 11 of 91 remaining augmentations + 1 levels of NeuroFlux.
  Augs: ["Speech Processor Implant", "Hacknet Node Kernel Direct-Neural Interface", "Social Negotiation Assistant (S.N.A)", "Nuoptimal Nootropic Injector Implant", "ADR-V1 Pheromone Gene", "Speech Enhancement", "Hacknet Node CPU Architecture Neural-Upload", "Synaptic Enhancement Implant", "Hacknet Node Cache Architecture Neural-Upload", "Hacknet Node NIC Architecture Neural-Upload", "Neurotrainer I", "NeuroFlux Governor"]
2023-01-10T00:11:55 Invoking ascend.js at 6h 6m 37s   since last aug to install: 2 of 70 remaining augmentations + 10 levels of NeuroFlux.
  Augs: ["LuminCloaking-V1 Skin Implant", "LuminCloaking-V2 Skin Implant", "NeuroFlux Governor"]

**Comment by alainbryden** [comment]
This is all working as designed. The longer you are in a bitnode, the more
the aug count required to reset is reduced. This is a necessary design to
strike a balance in bitnodes intentionally setup slow reputation gain (such
as late BN12.xs)

If you wish to configure it, there is a setting
--reduced-aug-requirement-per-hour which defaults to 0.5

**Comment by gbreeden01** [comment]
OK, it just seems weird that it installed 4 + 9NF on the 2nd iteration in my first example above (14ish hours into the BN) and then 2 + 10NF the one following. Anyway, thanks for the replies - I appreciate it.
