### ISSUE TITLE
sleeve.js

### ISSUE THREAD

**Issue by JCStrainer** [alainbryden/bitburner-scripts#266]
![image](https://user-images.githubusercontent.com/5628185/214535769-76657e28-a5b7-4d3c-bbe3-6e0d90c07a3c.png)

I have this recurring error in sleeve.js

**Comment by alainbryden** [comment]
You're playing an old version of the game. The latest version of the game
(available on steam or the bitburner-official github io) required changes
to the scripts that are backwards-incompatible. See the game's discord for
details.
