### ISSUE TITLE
WARNING: autopilot.js Caught (and suppressed) an unexpected error: Cannot access 'pid' before initialization

### ISSUE THREAD

**Issue by j-o-e-s** [alainbryden/bitburner-scripts#267]
Receiving this error mid game after completing a BN. Cycles every few seconds.  Solution is to kill all running scripts then manually progress.

Progress so far:  You are currently earning SF13.2, and you already own the following source files: 1.3, 2.2, 4.3, 5.3, 7.1, 8.2, 9.3, 10.3, 11.3, 13.1.

**Comment by alainbryden** [comment]
Can you upload a save that reproduces the issue?

**Comment by alainbryden** [comment]
Sorry, I've tried loading that save and got the following error:
![image](https://user-images.githubusercontent.com/2285037/217987843-5dd5ff88-8baf-4a3c-9d07-3b88641bc191.png)

Looking at the file you uploaded, it is indeed plain text JSON and not base64 encoded.

If you are able to reproduce the issue, I need you to go into options > export game to produce a file that I can then load up, play, and debug:
![image](https://user-images.githubusercontent.com/2285037/217988052-217cf684-7138-4af0-8044-709db7524142.png)
