### ISSUE TITLE
Move "Heads Up" toast to Overview Panel

### ISSUE THREAD

**Issue by j-o-e-s** [alainbryden/bitburner-scripts#268]
Is there a way to move the "Heads Up: autopilot will reset in ##m ##s" to the Overview panel as either a countdown or progress bar?  The constant popups make it difficult to access the Hacknet server list or any page were text/buttons are shown on the bottom right.

**Comment by alainbryden** [comment]
It is intentionally very, very obtrusive. If you are trying to manually
interact with the game while autopilot is running, **especially** if it's
about to ascend for you, you're going to have a bad time.

Realistically you shouldn't be trying to attempt anything (especially make
any purchases on your own) with a reset looming, or you might subvert
whatever progress autopilot was intending to make.

I suggest disabling autopilot while you are "flying manual".
