### ISSUE TITLE
Scripts behaves strange when window is minimized.

### ISSUE THREAD

**Issue by kotenok2000** [alainbryden/bitburner-scripts#273]
I see this in log
Doing 'field' work for "Daedalus" until 462,491 rep. Currently at 147,898, earning 11.500 rep/sec. (ETA: 7h 35m 56s)
WARNING: work-for-factions.js caught an unhandled error in its main loop. Trying again in 5 seconds...
The faction "Daedalus" does not support any of the known work types. Cannot work for this faction!
INFO: Starting main work loop with scope: 0...
Donations already unlocked for "Netburners". You should buy access to augs. Skipping working for faction...
Donations already unlocked for "Tian Di Hui". You should buy access to augs. Skipping working for faction...
Faction "Daedalus" Highest Aug Req: 2,500,000, Current Favor (0.00/150.00) Req: 462,491
INFO: Detected that "hacking" gives more rep than previous work "field". Switching...
Doing 'hacking' work for "Daedalus" until 462,491 rep. Currently at 148,666, earning 61.822 rep/sec. (ETA: 1h 24m 36s)
Doing 'hacking' work for "Daedalus" until 462,491 rep. Currently at 152,452, earning 0.000 rep/sec. (ETA: forever (Infinity))
Doing 'hacking' work for "Daedalus" until 462,491 rep. Currently at 156,210, earning 0.000 rep/sec. (ETA: forever (Infinity))
Doing 'hacking' work for "Daedalus" until 462,491 rep. Currently at 160,007, earning 62.113 rep/sec. (ETA: 1h 21m 10s)

**Comment by alainbryden** [comment]
I'm going to chop this up to the browser window getting throttled when minimized, which is a common issue with browser-based games. Nothing breaks per se, but timers don't fire so timing-related code (such as calculating rep/second) and progress generally behaves unpredictably.

**Comment by kotenok2000** [comment]
Even on steam version?

**Comment by alainbryden** [comment]
Yes, the steam version runs in a program called "electron" which is essentially just google chrome skinned to look like a standalone application.
