### ISSUE TITLE
Stockmaster.js

### ISSUE THREAD

**Issue by BradynMelser** [alainbryden/bitburner-scripts#274]
So, full disclosure, I am not a coder and I haven't played Bitburner in almost a year. So most of my scripts don't work now... I was trying your Stockmaster.js script and I was getting an error. 
"Failed to resolve module specifier "./helpers.js". Invalid relative url or base scheme isn't hierarchical.
stack:
TypeError: Failed to resolve module specifier "./helpers.js". Invalid relative url or base scheme isn't hierarchical."

I have copied over you helpers.js script as well. This didn't seem to fix it. I am unsure what this error even means.

**Comment by alainbryden** [comment]
I think you would need both scripts in your root folder for that import
path to work.

If you want to put them in a folder, use my git-pull.js script, there's an
argument to adjust everything to use folder paths.
