### ISSUE TITLE
Add flag to hacknet upgrade script

### ISSUE THREAD

**Issue by XTheIronFistX** [alainbryden/bitburner-scripts#277]
Could you add a flag to the hacknet upgrade script to only allow it to upgrade RAM for situations where hash production isn't worth it

**Comment by alainbryden** [comment]
How come? Upgrading RAM also improves hash production.

**Comment by XTheIronFistX** [comment]
I know it improves hash production but I'm in BN 8 where hash production is always 0

**Comment by XTheIronFistX** [comment]
I did notice that setting stock manipulation on daemon automatically is still on the TODO list. In addition with stock manipulation focus and allowing the use of hacknet servers the daemon script seems to prioritize the hacknet servers. That's why I was asking for the flag. I guess is it actually beneficial to buy/upgrade servers on BN 8?

**Comment by alainbryden** [comment]
It is, insofar as hacking remains useful in BN8 (not for income, but for
EXP and potentially stock manipulation, as you mentioned). Perhaps that is
why I left it as an enabled script for BN8, but there should at least be a
reserve or budget in play to prevent it from using an overwhelming amount
of the scarce pre-4S income. I imagine a flag merely asking it not to
upgrade hacknet/hashnet RAM alone would not make things any better. Without
further intervention, it would still spend nearly just as much continuing
to upgrade the hashnet level and cores, so we should focus on whether the
budget is being set appropriately.  If you are seeing any signs that it is
consuming a significant proportion of your income pre-4S, maybe that's the
takeaway I can aim to address.

Alain Bryden
