### ISSUE TITLE
Work for faction keeps restarting same job denying infiltration rewards 

### ISSUE THREAD

**Issue by XTheIronFistX** [alainbryden/bitburner-scripts#278]
As stated in the title during certain times when performing infiltrations immediately after the infiltration is finished the work for factions script will restart the same job thus changing the focus screen to the job before any chance of me picking the reward from infiltration. Would it be possible to add a delay preventing work from factions from taking away focus so quickly

**Comment by alainbryden** [comment]
Run with --no-focus

**Comment by Schadrach** [comment]
Doesn't help.  It's specifically jobs, not doing faction work and work-for-factions doesn't seem to respect --no-focus for jobs.

**Comment by alainbryden** [comment]
I know what's up here. There's a TODO there that was waiting on a game update to be pushed:
```js
// TODO: BITBURNER BUG: Game currently inverting this argument. Fix as soon as the game is updated. 
let focusArg = shouldFocus ? false : true; // TODO: REMOVE ON BUG FIX
if (await getNsDataThroughFile(ns, `ns.singularity.workForCompany(ns.args[0], ns.args[1])`, null, [companyName, focusArg])) {
    ...
```
I'm assuming the game has been updated to fix that bug and I can now remove the workaround.
