### ISSUE TITLE
sleeve.js 

### ISSUE THREAD

**Issue by mcxerxes82** [alainbryden/bitburner-scripts#280]
WARNING: sleeve.js Caught (and suppressed) an unexpected error in the main loop: Error: ns.read('/Temp/sleeve-getSleeveStats-all.txt') returned a bad result: "ERROR: REMOVED FUNCTION ERROR /Temp/sleeve-getSleeveStats-all.txt.js@home (PID - 19331) sleeve.getSleeveStats: Function removed in v2.2.0. Please use sleeve.getSleeve instead. Stack: /Temp/sleeve-getSleeveStats-all.txt.js:L-1@unknown /Temp/sleeve-getSleeveStats-all.txt.js:L2@Module.main". Script: /Temp/sleeve-getSleeveStats-all.txt.js Args: [0,1] Command: ns.args.map(i => ns.sleeve.getSleeveStats(i)) The script was likely passed invalid arguments. Please post a screenshot of this error on discord. at asError (home/helpers.js:301:45) at autoRetry (home/helpers.js:315:23) at async getNsDataThroughFile_Custom (home/helpers.js:172:22) at async getNsDataThroughFile (home/helpers.js:137:12) at async dictSleeveCommand (home/sleeve.js:155:48) at async mainLoop (home/sleeve.js:157:23) at async Module.main (home/sleeve.js:65:15) at async T (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1049459) ns.read('/Temp/sleeve-getSleeveStats-all.txt') returned a bad result: "ERROR: REMOVED FUNCTION ERROR /Temp/sleeve-getSleeveStats-all.txt.js@home (PID - 19331) sleeve.getSleeveStats: Function removed in v2.2.0. Please use sleeve.getSleeve instead. Stack: /Temp/sleeve-getSleeveStats-all.txt.js:L-1@unknown /Temp/sleeve-getSleeveStats-all.txt.js:L2@Module.main". Script: /Temp/sleeve-getSleeveStats-all.txt.js Args: [0,1] Command: ns.args.map(i => ns.sleeve.getSleeveStats(i)) The script was likely passed invalid arguments. Please post a screenshot of this error on discord.

**Comment by alainbryden** [comment]
This was fixed in #258 - you must be using an old version
