### ISSUE TITLE
Bug in checkOnRunningScripts() invoking gangs.js without arguments

### ISSUE THREAD

**Issue by AssenD** [alainbryden/bitburner-scripts#306]
Hi Alain,

With all due respect, I think I found a bug/mistake in autopilot.js -> checkOnRunningScripts() 
when invoking gangs.js - there are no arguments:
`if (playerInGang && !findScript('gangs.js'))
            launchScriptHelper(ns, 'gangs.js');`

I think there should be passed `rushGangsArgs` too:
`if (playerInGang && !findScript('gangs.js'))
            launchScriptHelper(ns, 'gangs.js', rushGangsArgs);`

**Comment by alainbryden** [comment]
Hey @AssenD 

At first glance, I agreed with you, but it turns out the `rushGangsArgs` is really confusingly named in this context.
A better name would be `rushGangsArgsForWorkForFaction` - since those args are being prepped for the subsequent call to `work-for-factions.js` a few lines lower.

**Comment by AssenD** [comment]
Yes, on second read I saw it too :), sorry to bother you!
