### ISSUE TITLE
Autopilot destroy bitnode bug

### ISSUE THREAD

**Issue by samohtGTO** [alainbryden/bitburner-scripts#307]
when the autopilot tries to destroy the bitnode it hasnt done the required backdoors

**Comment by alainbryden** [comment]
Going to need more details or a save to reproduce. I haven't seen an issue here.

Note that there is currently a bug in the game itself that doesn't run callback scripts after a BN is destroyed, but the way you worded this suggests you saw something different.

**Comment by alainbryden** [comment]
Discussed on iscord - not our bug

**Comment by samohtGTO** [comment]
i asked  it in dizzy and got the answer to the bug it just randomly happen that after i stoped and run the backdoors script it worked

**Comment by alainbryden** [comment]
Leaving this open until I remember exactly what code gets admin rights on WD, it's not clear here, but it is a requirement.

**Comment by samohtGTO** [comment]
it might be just a bug where it didnt had enough ram to execute it

**Comment by alainbryden** [comment]
> it might be just a bug where it didnt had enough ram to execute it

Maybe, if one only got SF 4.1 but moved on to other BNs without 4.3 - all singularity scripts would then cost 16x as much.

That said, it's hard to imagine getting to the end of the Bitnode (ready to destroy) without having naturally purchased enough home RAM to run whatever you want.
