### ISSUE TITLE
Bug in spend-hacknet-hashes.js

### ISSUE THREAD

**Issue by AssenD** [alainbryden/bitburner-scripts#309]
On row 70 
`while (success && ns.hacknet.numHashes() > (spendAllHashes ? getMinCost(purchases) : capacity - reserve)) {`
logic is reversed. 

It should be:
`while (success && ns.hacknet.numHashes() > (!spendAllHashes ? getMinCost(purchases) : capacity - reserve)) {`

or maybe better:
`while (success && ns.hacknet.numHashes() > (spendAllHashes ?  capacity - reserve : getMinCost(purchases))) {`

**Comment by alainbryden** [comment]
It looks right to me.

Remember that "spendAllHashes" is linked to the "liquidate" parameter, so if you run with --liquidate, you want to spend all your hashes, not save any of them. If not, then you only want to spend enough hashes that you aren't going to "waste" them (`capacity - reserve`).

The above while loop is saying: "IF we're spending all hashes, keep looping (and buying things) so long as we can afford the cheapest purchasable thing". This is what current ternary achieves.

**Comment by alainbryden** [comment]
Yes, running multiple spending scripts in `--liquidate` mode will often result in them "fighting" one-another for hashes. It sometimes works out if they are both exclusively buying something whose cost scales with each purchase, but the "intended" way to support this was to run a single script with multiple "--spend-on" arguments specified one after the other (as in the last example).

Still, if you got this to work to your liking by removing `--liquidate` from the aliases, that's great too. The end result in that case will likely be that your hash balance sits near your hash capacity at all times, and all running "spend" scripts would end up randomly taking turns purchasing what they're after each time the capacity is about to be hit.
