### ISSUE TITLE
RAM usage error

### ISSUE THREAD

**Issue by Realswitzer** [alainbryden/bitburner-scripts#312]
`Error while calculating ram usage for this script.`

In editor, it calculates RAM as "`Syntax Error`"

This seems to affect all scripts.

**Comment by alainbryden** [comment]
It seems like pulling the scripts has gone awry. People often have issues when they try to download the scripts to a sub-folder, as the game often changes how it deals with directories and breaks old import statements,

Try using git-pull.js to download the scripts from scratch, and if you can stand to, avoid downloading to a sub-folder, and it might fix the issue.

**Comment by Realswitzer** [comment]
Forgot to check this again, previous attempt ran at `~/git-pull.js`, tried it again and it worked. Unsure what caused it unfortunately, since it wasn't a sub-folder problem.
In any case, thanks for the help and fast response.
