### ISSUE TITLE
Make work-for-factions.js display remaining time also considering sleeves. [enhancement]

### ISSUE THREAD

**Issue by soulbreather** [alainbryden/bitburner-scripts#316]
It would be nice if the _work-for-factions.js_ script would account for _sleeves_ when calculating the time remaining until a promotion or accomplishment.

**Comment by alainbryden** [comment]
It already does. The game no longer tells us our rep/sec, so we measure it,
and that measurement includes all sources of rep.

**Comment by soulbreather** [comment]
I see, it would sometimes estimate about twice the rep/sec gained by the player. I guess that would be the estimation of sleeve + local.
