### ISSUE TITLE
Provide an option to sync player stats to an external location

### ISSUE THREAD

**Issue by chrisagiddings** [alainbryden/bitburner-scripts#319]
_As a Bitburner player on the go
I want to check my current Bitburner stats as managed by Alain's bitburner-scripts
So my obsession with the game is fed, and current_

I'd like a nice easy way to check on my Bitburner stats (money, income rate, nodes, augments, home system details, factions, etc) periodically via a tool like Google Drive, OneDrive, or iCloud Drive so I don't have to be at my PC.

If I happen to be at the office and want to check my stats, or in class, or at a family function and I want a distraction, what better way than to consider my Bitburner progress!

The data could take the form of JSON, markdown, or even simple HTML.

**Comment by alainbryden** [comment]
An understandable request, but I've always solved this sort of need with remote desktop software like "TeamViewer" or "AnyDesk". They have desktop and mobile apps that let you remotely check in on your computer by essentially mirroring your screen to your device. It's not as DIY as your suggestion, but certainly easier. Check it out!
