### ISSUE TITLE
autopilot stuck in constant reset

### ISSUE THREAD

**Issue by jbedgood** [alainbryden/bitburner-scripts#326]
recently when running autopilot it just keeps cycling through "autopilot is going to reset in 5m" count down and start all over again.

How do I clear this up?

**Comment by alainbryden** [comment]
Autopilot resets its timer each time you are able to afford a new
augmentation (to avoid resetting too soon if your income recently spiked).
If you want to confirm or deny whether that's the case, open the tail logs
for autopilot and show us the last 10 or so messages it printed.

**Comment by jbedgood** [comment]
Where is the tail log?

**Comment by alainbryden** [comment]
Every scrip that runs in bitburner has its own log window. You access it by
running the `tail` command and passing in the name of the script - hence
"tail log"

Autopilot's log window should be open by default, unless you closed it. If
so, run 'tail autopilot.js' to get it back.

**Comment by jbedgood** [comment]
well it seems to have cleared itself finally. It cycled through the reset countdown like 5 times and finally completed a reset and is running now.
