### ISSUE TITLE
Git-Pull needs to use current working directory

### ISSUE THREAD

**Issue by magius96** [alainbryden/bitburner-scripts#327]
Reproduction:  In a new game  "nano /scripts/alainbryden/git-pull.js".  Paste in script from git-pull.js.  Save the file then go to terminal and execute the newly created script.

Actual:  All js files from alainbryden/bitburner-scripts are downloaded to home directory.

Expected:  All js files from alainbryden/bitburner-scripts are downloaded to /scripts/alainbryden/

Reason:  Some users, like myself like to keep our scripts a bit organized.  This would help me to have them organized from the download instead of having to manually move the files afterwards.

**Comment by alainbryden** [comment]
The `--subfolder` argument supports downloading to a folder of your choosing (which in turn requires editing downloaded scripts to fix their absolute path references to match the subfolder as well).

I believe the `ns.getScriptName()` function can be used to get the current running script's full path - so if you wanted to make a PR changing the default behaviour (when no `--subfolder` argument is specified) to match the path of the current running script (git-pull.js), I think that would be a fair change.
