### ISSUE TITLE
Stanek's gift not activated automatically

### ISSUE THREAD

**Issue by dacas3** [alainbryden/bitburner-scripts#335]
Stanek's gift has to be accepted before buying augmentations. That doens't happen.

As I understand it, faction-manager.js should take care of that.

Is that automatically invoked before buying augmentations? Any tips of what I should troubleshoot?

**Comment by alainbryden** [comment]
Could you please provide a save that reproduces the issue on running ascend.js? I recently did some work on the scripts and didn't see this happening.

**Comment by dacas3** [comment]
Sure, I've made an experiment to test that.

The ascend gives these lines in the beginning when I run it (it's a fresh bitnode, didn't buy anything)

> ascend.js: Accepting Stanek's Gift (if this is the first reset)...
> ascend.js: WARNING: It looks like we can't get Stanek's Gift. (Did you manually purchase some augmentations?)

Here's the save I used, so you can reproduce:
[bitburnerSave_1708073523_BN1x4.json](https://github.com/alainbryden/bitburner-scripts/files/14308663/bitburnerSave_1708073523_BN1x4.json)

**Comment by dacas3** [comment]
Just wanted to confirm that I've consistently recreated this scenario every time at the start of a bitnode, with ascend saying the same thing; that it wonders if I manually had bought some augmentions (which is not the case)

**Comment by SirLovi** [comment]
Seems to be fixed now in v2.6.0

**Comment by alainbryden** [comment]
Yep the whole thing was due to this game bug, which is now fixed: https://github.com/bitburner-official/bitburner-src/issues/1000
