### ISSUE TITLE
Bitburner now kills all scripts on casino save scumming.

### ISSUE THREAD

**Issue by Heratiki** [alainbryden/bitburner-scripts#342]
Title pretty much says it all.

Running casino.js will eventually earn you money but after a reload you have to restart the script again and it stops all other activity.  I haven't dug into this too much to see if it's something Bitburner now does or if it's something the script does.

**Comment by alainbryden** [comment]
Have you ever used the "kill all scripts" button in game? If so each reload
keeps that option, and you have to restart the game normally to make it
stop.

**Comment by Heratiki** [comment]
One of my first scripts was as recursively killing all of my running scripts before realizing the function of the button. So I never really use it. I'll give it a look, thank you.

**Comment by lessfoobar** [comment]
what you mean with restart the game? like soft reset or ?

**Comment by alainbryden** [comment]
No, just shut it down and relaunch it without the kill all scripts option.
If you're in a browser, clear that flag from the url and reload.

**Comment by Heratiki** [comment]
Thank you for the help here.  I wasn't understanding initially what you had suggested.  Now it works as intended. :-)
