### ISSUE TITLE
Failed to exec /Tasks/contractor.js (BB ver. 2.6.2)

### ISSUE THREAD

**Issue by tatzio** [alainbryden/bitburner-scripts#344]
This started happening on ver. 2.6.2
``` RUNTIME ERROR
daemon.js@home (PID - 6954)

Failed to exec /Tasks/contractor.js on home with 1 threads. This is likely due to having insufficient RAM. Args were: []
stack:
Error: Failed to exec /Tasks/contractor.js on home with 1 threads. This is likely due to having insufficient RAM. Args were: []
    at home/daemon.js:541:28
    at autoRetry (home/helpers.js:337:77)
    at async exec (home/daemon.js:538:17)
    at async arbitraryExecution (home/daemon.js:1424:19)
    at async tryRunTool (home/daemon.js:509:23)
    at async runPeriodicScripts (home/daemon.js:476:17)
    at async main (home/daemon.js:367:5)
    at async R (https://bitburner-official.github.io/dist/main.bundle.js:9:401629)

**Comment by tupcakes** [comment]
also seeing this.

**Comment by HaiNick** [comment]
I've run into an error related to a syntax change in the file /Tasks/contractor.js. After some digging, I discovered how to fix it by tweaking the import statement.

`import { getFilePath, getNsDataThroughFile, disableLogs, scanAllServers } from './helpers.js'`

`import { getFilePath, getNsDataThroughFile, disableLogs, scanAllServers } from 'helpers.js'`

You'll need to make the same change in the following files:

- /Tasks/backdoor-all-servers.js
- /Tasks/ram-manager.js

Updating these import statements should resolve the errors. This is the best fix I've found so far, but there might be other bugs lurking around. If anyone else has been encountering this issue, try making these changes.

**Comment by tatzio** [comment]
> `import { getFilePath, getNsDataThroughFile, disableLogs, scanAllServers } from 'helpers.js'`
> 
> You'll need to make the same change in the following files:
> 
> * /Tasks/backdoor-all-servers.js
> * /Tasks/ram-manager.js

Can confirm this fixed my issue, THANKS @HaiNick
