### ISSUE TITLE
suggestion work-for-factions & casino

### ISSUE THREAD

**Issue by herrxyz** [alainbryden/bitburner-scripts#349]
suggestion: after installing augs, first level stats to like 10 or 20, then do crime to get more than 200k money, then do casino, then do "all the other work for factions stuff"

**Comment by alainbryden** [comment]
- Needs more clarity, this already sounds a lot like what we do (university and crime are already both used to level stats, casino is already run when we feel it is safe to do so)
- Needs a more balanced consideration of how this affects the balance in other BNs.
