### ISSUE TITLE
Sleeve.js incorrectly counting bitburner contract count

### ISSUE THREAD

**Issue by waffleattack** [alainbryden/bitburner-scripts#366]
I was investigating my sleeves count, specifically why my sleeves were sometimes getting stuck to idle, and I realized that the bladeburnerContractCount in sleeve.js is wrong. After logging the value of bladeburnerContractCount, I saw that for whatever reason it would always be an empty map. (but bladeburnerContractChance would give the correct values)

(The change I made to log the value in mainLoop())
```js      
 bladeburnerContractCounts = await getNsDataThroughFile(ns,
            'Object.fromEntries(ns.args.map(c => [c, ns.bladeburner.getActionCountRemaining("contract", c)[0]]))',
            '/Temp/sleeve-bladeburner-contract-counts.txt', sleeveBbContractNames);
        log(ns, bladeburnerContractCounts)
```

results in the script logs being filled with just {}

**Comment by alainbryden** [comment]
Funny, this bug was hidden until this PR was submitted a short while back: https://github.com/alainbryden/bitburner-scripts/pull/341

I guess two wrongs were making a right. Now we have to figure out how to fix the other wrong

**Comment by alainbryden** [comment]
If your map prints empty, does that mean sleeveBbContractNames is empty?

**Comment by waffleattack** [comment]
the sleeveBbContractNames contains `["Tracking","Bounty Hunter","Retirement"]`, and bladeburnerContractChance is giving the correct values (or at least valid numbers), so its something specific about the counting

**Comment by alainbryden** [comment]
I have a feeling that this is because getActionCountRemaining can return `Infinity` for some actions, and JSON.stringify does not support Infinity (which has always been wild to me) - so the serialize / deserialize process of the response could be breaking.

**Comment by alainbryden** [comment]
Figured it out, it was a more overt bug than I thought, I was treating the result of getActionCount as an array (likely a copy-paste error from the getSuccessChance implementation), but it's a simple number
