### ISSUE TITLE
Autopilot.js gets stuck on xp-only when set via timer logic

### ISSUE THREAD

**Issue by shrut-z** [alainbryden/bitburner-scripts#371]
Autopilot seems to never relaunch daemon.js normally again after the time is up
I noticed a few days ago that it was spending a lot of time on xp-only mode but I thought maybe it was because of Daedalus logic. Now this is happening on a fresh BN.

I've also never seen the "Time is up for "xp-mode", Relaunching daemon.js..." relaunch message printed
![WhatsApp Image 2024-10-14 at 10 20 38_fc8ae947](https://github.com/user-attachments/assets/48bc804e-1957-4387-8e9b-16e38eee5ece)

**Comment by alainbryden** [comment]
Oops, thanks for the heads up. I think I know why
