### ISSUE TITLE
Hacket upgrade not running as configured in daemon

### ISSUE THREAD

**Issue by archraziel** [alainbryden/bitburner-scripts#39]
I realized that hacknet-upgrade-manager.js isn't being executed as intended by daemon.js

In daemon.js we have this configuration, but in the logs it just calling the 8h one as show in the picture.

```
// Buy every hacknet upgrade with up to 4h payoff if it is less than 10% of our current money or 8h if it is less than 1% of our current money
        { interval: 32000, name: "hacknet-upgrade-manager.js", shouldRun: shouldUpgradeHacknet, args: () => ["-c", "--max-payoff-time", "4h", "--max-spend", ns.getServerMoneyAvailable("home") * 0.1] },
        { interval: 33000, name: "hacknet-upgrade-manager.js", shouldRun: shouldUpgradeHacknet, args: () => ["-c", "--max-payoff-time", "8h", "--max-spend", ns.getServerMoneyAvailable("home") * 0.01] },

```

![image](https://user-images.githubusercontent.com/68472054/150382362-2d980e0a-c6d2-4a3f-b806-83b76c3517db.png)

Also, how can I set it to be very agressive regarding hacknet upgrades?
I tried to set it to 30m and 0.5 of my money but still not buying upgrades

**Comment by alainbryden** [comment]
Check your currently running scripts on home. Is another one still running? `shouldUpgradeHacknet` is configured to only let 1 of the 3 run at a time.

**Comment by alainbryden** [comment]
Also, try setting tail: true on your modified version. I'm betting it is
running, but there's no purchases remaining that pay off in under 30
minutes.

**Comment by archraziel** [comment]
Using the default daemon.js with no modifications. I don't see it running even when the 8h appears on the log.

![image](https://user-images.githubusercontent.com/68472054/150387413-584dec59-4714-4b49-a8c5-6893d8caba80.png)




this is the tail from the hacknet-upgrade-manager.js that is configured inside the asynchronousHelpers variable
     `   { name: "hacknet-upgrade-manager.js", tail: true, args: ["-c", "--max-payoff-time", "1h"] }, // Kickstart hash income by buying everything with up to 1h payoff time immediately`


![image](https://user-images.githubusercontent.com/68472054/150388523-5f8e91c8-f7c6-4e25-98c8-e3dc6b2c9831.png)


I don't think I made it clear, but the problem is with the ones inside periodicScripts variable, the line with 4 hours just run when I comment the line with 8 hours.


When I change to 1m and to use 0.9. I get this tail. I also added a log on the hacknet upgrade script. I am confused but I think there is something wrong, I am sending 1minute  payoff but is comparing with 1hour:14minutes. 

``` if (payoffTimeSeconds > maxPayoffTimeSeconds) {
        log(ns, `payoffTimeSeconds: ${payoffTimeSeconds} and maxPayoffTimeSeconds: (${maxPayoffTimeSeconds})`);
        log(ns, `The next best purchase would be ${strPurchase} but the ${strPayoff} is worse than the limit (${formatDuration(1000 * maxPayoffTimeSeconds)})`);
        return false; // As long as maxPayoffTimeSeconds doesn't change, we will never purchase another upgrade
    }
```
    
    
![image](https://user-images.githubusercontent.com/68472054/150391077-9ca02f1d-a612-4204-98cb-04e5e918db96.png)

**Comment by archraziel** [comment]
A few more info about the variable that make the 
 `let payoffTimeSeconds = 1 / (hashDollarValue * (shouldBuyNewNode ? newNodePayoff : bestUpgradePayoff));`
hashDollarValue: 250000 
shouldBuyNewNode: false
newNodePayoff: 9.705877567456382e-10 
 bestUpgradePayoff 1.0349621569813014e-9

**Comment by alainbryden** [comment]
I'm not sure you understand what the payoff time means it will only buy
upgrades that will pay for themselves in that amount of time. You are
setting it too low. If you want to buy more upgrades, you have to be
willing to buy upgrades that take hours or days to pay off.

**Comment by archraziel** [comment]
Jeez dude, mb! 
I put it 24h with 0.9 and now is upgrading very agressive. I will close this.

I am deeeply sorry for the misunderstood. Thank you very much
