### ISSUE TITLE
Missing Temp Files

### ISSUE THREAD

**Issue by Skyl3lazer** [alainbryden/bitburner-scripts#4]
When running several scripts such as work-for-factions (via daemon), they crash with an error like 

FAIL: (0 retries remaining): ns.read('/Temp/-462713546-data.txt') somehow returned undefined or an empty string

**Comment by Skyl3lazer** [comment]
This seems to relate to retrieving gang information before BN2

**Comment by alainbryden** [comment]
Fixed just today. They will still raise errors as they try to see if the functionality is available, but they won't crash anymore.
