### ISSUE TITLE
faction-manager.js: NeuroFlux Governor Level -1

### ISSUE THREAD

**Issue by rraumberger** [alainbryden/bitburner-scripts#416]
Something seems off in the `faction-manager` NF calculation or is a NF level of `-1` actually a thing?
I haven't had time to look into this yet.

Current BitNode: 14.1 (First run)

![image](https://github.com/user-attachments/assets/bece4797-c01f-4d95-a1a2-75ed0a9af832)

**Comment by rraumberger** [comment]
It's possible that this has the same cause as #406. If so, please close this as duplicate.

**Comment by alainbryden** [comment]
I'll leave it open for now as it's a simple case to reproduce, but yeah I believe it's the same root cause, missing a bitnode multiplier in the equation
