### ISSUE TITLE
daemon.js: "hack stole 0 money, may be a missfire"

### ISSUE THREAD

**Issue by starg3n** [alainbryden/bitburner-scripts#420]
not sure what this is about.
If it matters, I'm playing on the web version, [bitburner official](https://bitburner-official.github.io/).
![Screenshot 2024-10-31 10 42 18 AM](https://github.com/user-attachments/assets/6d007850-44d6-4b2b-b41c-7c4627daace1)

**Comment by alainbryden** [comment]
It's just a warning, batch scripts have to be precisely timed and sometimes
misfires happen. If you aren't trying to fine-tune batching you can ignore
it. You can even configure daemon.js with --silent-misfires to suppress it.
