### ISSUE TITLE
Bladeburner Activities 'undefined'

### ISSUE THREAD

**Issue by supermopf** [alainbryden/bitburner-scripts#43]
Hey,

I'm currently in BN6 and found out that work-for-factions.js has a problem with Bladeburners:

```
The last "Bladeburners" aug is only 62.500 rep, not worth grinding 459.796 rep to unlock donations.

Faction "Bladeburners" Highest Aug Req: 62.500, Current Favor (5.1686/150) Req: 459.796

Doing 'undefined' work for "Bladeburners" until 62.500 rep. Currently at 0, earning 0.000 rep/sec. (ETA: Infinityh)

```

**Comment by archraziel** [comment]
If I am not mistaken, Bladeburner faction rep can only be gained doing bladeburner activities and not doing work like the script does.

**Comment by alainbryden** [comment]
Hey, I haven't played Bladeburner BNs yet, so if there's a PR you can make
to tweak the config so it's not a problem, feel free to do so and I'll
approve it.
