### ISSUE TITLE
Bug: Autopilot not backdooring world daemon on BN5.2.

### ISSUE THREAD

**Issue by noirsoldats** [alainbryden/bitburner-scripts#443]
I'm in BN5.2, I have the red pill, only missing two augs, hack level 24,000+, got the notification that world daemon was available to backdoor.. but the autopilot isn't automatically doing it and I can't figure out why. 

I know in BN10 it will intentionally wait for you to get all the sleeves, but is it waiting for something in BN5.2?
[bitburnerSave_1732167328_BN5x2.json.gz](https://github.com/user-attachments/files/17840410/bitburnerSave_1732167328_BN5x2.json.gz)

**Comment by alainbryden** [comment]
Thanks for reporting and for the save
