### ISSUE TITLE
Possible error in autopilot.js with checking income to see if casino.js needs to be run

### ISSUE THREAD

**Issue by uther3k** [alainbryden/bitburner-scripts#449]
While looking through my log file for autopilot.js, I came across the following entry.

[12-08-2024] INFO: Skipping running casino.js this augmentation, since our income ($88.720k/min) >= 5b/min

Since 88.720k/min is not more than 5b/min, it appears there is either an error with the income reported to the log or the formula checking if we're making more than 5b/min. 

Thank you for these scripts.  They have been very helpful to me.

**Comment by alainbryden** [comment]
Sorry - good news is this is just a display error. $88.720k was your computed income per millisecond since the start of the bitnode. If it had been correctly been displayed as "income per minute" it would be 5.32b / min.

I'll fix the code to display it correctly. Thanks for reporting!
