### ISSUE TITLE
daemon.js problem  

### ISSUE THREAD

**Issue by Brleaikde** [alainbryden/bitburner-scripts#451]
when I run  daemon.js script I keep getting this error Remote/hack-target.js omega-net 1734082540768 44887 Batch 11-hack 1 0 0 or hack failed to steal money.

**Comment by alainbryden** [comment]
This is only a "warning" and is normal. Misfires happen from time to time as your hack stat grows and hack cycles (especially those planned far in advance) complete with different timings than expected.

Unless you are seeing a steady stream of these warnings (e.g. one every second for several minutes) there's nothing to worry about.

If you are seeing dozens or hundreds of these warnings, then it's a sign your game is lagging. Check out [Bitburner #batching discord channel](https://discord.com/channels/415207508303544321/944647347625930762) for more info on misfires and why they are a fact of life.

---

Finally, if you find these annoying, create a new settings files with `nano daemon.js.config.txt` and give it the contents `{ 'silent-misfires': true }` - you'll never see a warning like this again.
