### ISSUE TITLE
"weak-target.js cannot be run because it does not have a main function"

### ISSUE THREAD

**Issue by Skyl3lazer** [alainbryden/bitburner-scripts#5]
Periodically, as well as several times on daemon first startup, the following message (or similar) will appear

RUNTIME ERROR
/Remote/weak-target.js@daemon-8
Args: ["syscore", 1640036309008, 1640036865632, 556624, "Batch 20-weak1", 0, 0]

/Remote/weak-target.js cannot be run because it does not have a main function.

**Comment by alainbryden** [comment]
This is a bug with the game itself. There's an open issue in the bitburner backlog.

**Comment by alainbryden** [comment]
https://github.com/danielyxie/bitburner/issues/1714

**Comment by calpa** [comment]
```
RUNTIME ERROR
/Remote/weak-target.js@silver-helix
Args: ["n00dles", 1641276819707, 1641276870211, 50504, "Batch 0-weak2", 0, 0]

/Remote/weak-target.js cannot be run because it does not have a main function.
```
