### ISSUE TITLE
Error In Targeting Loop

### ISSUE THREAD

**Issue by cullumar** [alainbryden/bitburner-scripts#53]
Hello - relatively newbie here, recently downloaded the full repository on a clean install and am giving it a shot in BN8.1 (Ghost of Wall Street).

After launching daemon.js either with or without arguments, I shortly get the warning:

"daemon.js: WARNING: Caught an error in the targeting loop: TypeError: Cannot read properties of undefined (reading 'name')"

This error pops continuously every 20 seconds or so, and it's not clear to me if it's a serious issue or even what it's trying to tell me.  Since 8.1 restricts all profit except from stock trading, I'm wondering if it's an issue with not buying or using player servers or hacknet nodes?

stockmanager.js appears to be functioning normally - no issues there

Any idea what I might be doing wrong to cause this error?  I have not purchase or delete any servers on this bitnode - certainly not while the script was running.

Thanks!

**Comment by Randshot** [comment]
> Hello - relatively newbie here, recently downloaded the full repository on a clean install and am giving it a shot in BN8.1 (Ghost of Wall Street).
> 
> After launching daemon.js either with or without arguments, I shortly get the warning:
> 
> "daemon.js: WARNING: Caught an error in the targeting loop: TypeError: Cannot read properties of undefined (reading 'name')"
> 
> This error pops continuously every 20 seconds or so, and it's not clear to me if it's a serious issue or even what it's trying to tell me. Since 8.1 restricts all profit except from stock trading, I'm wondering if it's an issue with not buying or using player servers or hacknet nodes?
> 
> stockmanager.js appears to be functioning normally - no issues there
> 
> Any idea what I might be doing wrong to cause this error? I have not purchase or delete any servers on this bitnode - certainly not while the script was running.
> 
> Thanks!

@cullumar Yeah, the bug was introduced in one of the recent commits, but it has been reverted for now, until a proper patch is going to be applied. Just re-download the `daemon.js`, and it should work just fine.

**Comment by cullumar** [comment]
Can confirm - I think I just got very unlucky with my download timing.  Re-downloading daemon.js appears to have fixed the issue.  Thank you!
