### ISSUE TITLE
ps(...).some is not a function

### ISSUE THREAD

**Issue by ininsicken** [alainbryden/bitburner-scripts#54]
Hi, I just tried to start using your scripts after pulling from github but when I put "run daemon.js" in my terminal I get this:

RUNTIME ERROR
daemon.js@home

ps(...).some is not a function
stack:
TypeError: ps(...).some is not a function
at whichServerIsRunning (daemon.js:289:46)
at tryRunTool (daemon.js:330:27)
at runStartupScripts (daemon.js:299:39)
at Module.main (daemon.js:272:49)

I'm not sure if there's something wrong in daemon.js or if I'm doing something wrong but it seems like it doesn't like the ps() function for whatever reason.

**Comment by alainbryden** [comment]
Ps is supposed to return an array, and some is in the array prototype. Back
up your changes then try a fresh `run git-pull.js` to see if it's something
you broke by accident.

**Comment by alainbryden** [comment]
It's also somewhat possible the game was updated to change the return value
of ps, but that would be a pretty big deal.

**Comment by ininsicken** [comment]
Yeah, I ran a fresh 'run git-pull.js' and then 'run daemon.js' and it gave almost the exact same thing:

RUNTIME ERROR
daemon.js@home

ps(...).some is not a function
stack:
TypeError: ps(...).some is not a function
at whichServerIsRunning (blob:https://danielyxie.github.io/0301ddbb-aab9-4274-b847-84a9dacb5424:289:46)
at tryRunTool (blob:https://danielyxie.github.io/0301ddbb-aab9-4274-b847-84a9dacb5424:330:27)
at runStartupScripts (blob:https://danielyxie.github.io/0301ddbb-aab9-4274-b847-84a9dacb5424:299:39)
at Module.main (blob:https://danielyxie.github.io/0301ddbb-aab9-4274-b847-84a9dacb5424:272:49)

**Comment by alainbryden** [comment]
Sorry, on my phone so this is spastic - but I just realized this is my own
'wrapper' for ps which is cache-backed, so this could be a bug in my code,
just odd that you're the first to encounter it!

**Comment by ininsicken** [comment]
All good, is there anything I can do to fix it?

**Comment by alainbryden** [comment]
Maybe tprint the JSON.stringify result of whatever ps is returning on that
line of code before attempting to call .some? Could give a hint.

**Comment by ininsicken** [comment]
I'm not familiar with javascript, is this an issue with just me or is this an issue with the code in daemon.js itself?

**Comment by alainbryden** [comment]
Seems to be just you (for now) so at the moment you're the only one who
could do aittle debugging and shed light on the root cause

**Comment by ininsicken** [comment]
Ah, it seems like I had other scripts that were still active even after I typed "killall" for whatever reason that were tampering with whatever that part of the code was trying to do, I just installed augmentations and then tried running daemon.js and it's working good, thank you!

**Comment by alainbryden** [comment]
Aah okay. Perhaps you had two copies of daemon running. This game does some
veeery weird things with shared globals for scripts that have the same name.
