### ISSUE TITLE
Sleeves only do crime

### ISSUE THREAD

**Issue by archraziel** [alainbryden/bitburner-scripts#55]
More of a question than a real issue.

Why is the other sleeves except 0 set to only do crime?
I read the bug mention on the [PR](https://github.com/alainbryden/bitburner-scripts/pull/47) but that would only happen if the sleeves are doing multi work. 

Is there also a problem if the sleeves do the same activity the sleeve 0 is doing?

**Comment by alainbryden** [comment]
Right, so the game doesn't let more than one sleeve work for the same
faction.

Sleeves can do one or two other things, like study or go to the gym, but I
haven't found a practical use case for now so I haven't coded any such
logic.
