### ISSUE TITLE
Contracts Bug

### ISSUE THREAD

**Issue by raziel420** [alainbryden/bitburner-scripts#6]
Error message is 
/Tasks/run-with-delay.js: Failed to spawn "/Tasks/contractor.js.solver.js" with args: [{[List of available contracts as arguments]}] (bad file name or insufficient RAM?)

Seems as though daemon is sending the wrong arguments to run-with-delay.js and it's trying to run contractor.js.solver.js instead of just contractor.js

**Comment by alainbryden** [comment]
This is likely happening because you don’t have the sufficient 17 GB of
free RAM to run the contract solver. Free up more RAM.

**Comment by raziel420** [comment]
Maybe because daemon is using it all for attacks?


[home ~/]> top

Script                                  PID       Threads         RAM Usage

daemon.js                               1         1               5.50GB

stats.js                                8         1               3.10GB

/Remote/weak-target.js                  1851      10              17.50GB

/Remote/weak-target.js                  1855      10              17.50GB

/Remote/weak-target.js                  1859      10              17.50GB

/Remote/weak-target.js                  1863      10              17.50GB

/Remote/weak-target.js                  1867      10              17.50GB

/Remote/weak-target.js                  1871      10              17.50GB

/Remote/weak-target.js                  2178      130             227.50GB

/Remote/weak-target.js                  2179      7               12.25GB

/Remote/weak-target.js                  2204      129             225.75GB

/Remote/weak-target.js                  2205      7               12.25GB

/Remote/weak-target.js                  2216      64              112.00GB

/Remote/weak-target.js                  2217      7               12.25GB

/Remote/weak-target.js                  2221      161             281.75GB

/Remote/grow-target.js                  2222      10              17.50GB

/Remote/weak-target.js                  2223      1               1.75GB

/Remote/grow-target.js                  2224      13              22.75GB

/Remote/weak-target.js                  2225      2               3.50GB

/Remote/weak-target.js                  2232      104             182.00GB

/Remote/weak-target.js                  2233      7               12.25GB

/Tasks/run-with-delay.js: Failed to spawn "/Tasks/contractor.js.solver.js" with args: [{"contract":"contract-76006-Netburners.cct","hostname":"rothman-uni","type":"Find Largest Prime Factor","data":935542566},{"contract":"contract-858219.cct","hostname":"stormtech","type":"Array Jumping Game","data":[3,6,8,8,3,7,5,0,5,0,2,0,10,3,6,7]},{"contract":"contract-561671.cct","hostname":"b-and-a","type":"Algorithmic Stock Trader II","data":[50,1,81,12,191,147,147,54,39,3,75,16,170,90,47,192,86]},{"contract":"contract-721112-NiteSec.cct","hostname":"ecorp","type":"Array Jumping Game","data":[0,10,2,9,7,0,0,0,9,2,9,0,4,9,7,2,0]},{"contract":"contract-301103-TianDiHui.cct","hostname":"infocomm","type":"Algorithmic Stock Trader III","data":[142,160,129,188,154]},{"contract":"contract-945133-Volhaven.cct","hostname":"infocomm","type":"Sanitize Parentheses in Expression","data":")(((((aa((()(()())(("},{"contract":"contract-434380.cct","hostname":"aerocorp","type":"Algorithmic Stock Trader II","data":[46,181,20,180,72]},{"contract":"contract-470092.cct","hostname":"zeus-med","type":"Find Largest Prime Factor","data":115559195}] (bad file name or insufficient RAM?)

**Comment by alainbryden** [comment]
Daemon has a setting `['reserved-ram', 32]` which defaults to leaving 32 GB of RAM free on `home` make sure not to lower that too much if you want to be able to run a bunch of sporadic scripts.

Aside from that, I've never seen any issues with spawning this, I use it all day every day on two accounts.

Instead of running "top" when it fails run "free" and see how much free ram there is on home. It has to be more than 11.6 GB + 2.6GB for "run with delay" - total 14.2 GB.

If it was just a temporary issue due to e.g. a lot of other sporadic scripts spawning at the same time, perhaps I can add an auto-retry logic to the "run-with-delay" helper.

**Comment by raziel420** [comment]
I'm not great with code, but I knew it wasn't a memory issue.  Even right after killing everything, same error.


```
[home ~/]> killall

Killing all running scripts

[home ~/]> run /Tasks/contractor.js

Running script with 1 thread(s), pid 17359 and args: [].

/Tasks/run-with-delay.js: Failed to spawn "/Tasks/contractor.js.solver.js" with args: [{"contract":"contract-133841-CentralIntelligenceAgency.cct","hostname":"silver-helix","type":"Subarray with Maximum Sum","data":[1,7,-10,0,8,4,-3,-3,-7,-7,5,1,10,-4,2,-9,1,9,-10,-2,8,3,-1,3,8,0,4,-6]}] (bad file name or insufficient RAM?)
```

To be fair, I just started this game a couple days ago, can't code for crap, and have no sources unlocked so far, so I know i'm getting a few errors because of source files.

**Comment by alainbryden** [comment]
Hmm, can you confirm you've got both contractor and solver in that Tasks
folder?

**Comment by raziel420** [comment]
AH there's my problem, I'm an idiot and didn't realize contractor.js.solver.js was a separate file entirely.   Consider this my request for a installer script.

**Comment by alainbryden** [comment]
I've updated git-pull.js now to automatically get all files in the target repository by default, so folks shouldn't have this same issue in the future. Thanks for sharing!
