### ISSUE TITLE
Bug: run daemon.js -x throws ERROR: Ran out of RAM to run /Remote/grow-target.js - 2 of 243 threads were spawned.

### ISSUE THREAD

**Issue by Durden-T** [alainbryden/bitburner-scripts#60]
run daemon.js -x 
ERROR: Ran out of RAM to run /Remote/grow-target.js - 2 of 243 threads were spawned.
Hi, is this error critical?

**Comment by Durden-T** [comment]
about 0.5 error/s

**Comment by Durden-T** [comment]
and this warning: WARNING: Cannot farm XP from n00dles, threads == 0 for allocated server daemon-7 with 0 GB free RAM

**Comment by alainbryden** [comment]
It sounds like perhaps you ran with `recovery-thread-padding` set to something other than 1 while your hack level and home ram are still too low. Check out the docs on this "The above alias is powerful when you are end-of-bn and your hacking skill is very high (8000+)".

Early game you should be running with default options only, excepting perhaps to crank up the default budget for purchasing hosts.
