### ISSUE TITLE
Feature: Add Unit Test for utilities

### ISSUE THREAD

**Issue by calpa** [alainbryden/bitburner-scripts#62]
Example: `bitburner-scripts/helpers.js`

```js
export function formatMoney(num, maxSignificantFigures = 6, maxDecimalPlaces = 3) {
    let numberShort = formatNumberShort(num, maxSignificantFigures, maxDecimalPlaces);
    return num >= 0 ? "$" + numberShort : numberShort.replace("-", "-$");
}
```

We may use `jest` to test functions to increase the stability of the system.

**Comment by manniL** [comment]
I second this. Either jest or [vitest](https://vitest.dev/) could be a nice fit 👍

**Comment by alainbryden** [comment]
I do all my coding in the game itself, (which obviously doesn't have a unit
test runner) so someone with VS integration will have to tackle this, and
ideally also edit git-pull.js to ignore tests so as not to bloat the save
file.

**Comment by alainbryden** [comment]
Closing this as won't do - as I've decided that this repo won't be tool-assisted.
