### ISSUE TITLE
unknown or unexpected option --utilization-trigger on ram-manager.js

### ISSUE THREAD

**Issue by deadpyxel** [alainbryden/bitburner-scripts#64]
With the latest version of the script I keep getting the following error:

![image](https://user-images.githubusercontent.com/8644691/158594165-516e7f15-ed6f-4476-a1ba-bd88c1667842.png)

The script in question really does not have the mentioned flag, only the `budget` and `reserve`.

I have tried a reload, but the problem persists between runs, is there any quick fix I can apply? I noticed the call to this script has changed on the last commit.

**Comment by axlmcc** [comment]
On my checkout of this repo, I rolled back to the commit just before this one to fix it. 

Export your save before running these commands, in case you run into any issues. For instance, the git-pull.js script can fail, if you've hit your API limit for the day.

```sh
[home ~/]> rm daemon.js # be sure to stop your existing daemon.js process before deleting
[home ~/]> run git-pull.js -t 1 --branch 87c3063e2ea713571c6990f2ec21b154ea650111
```

**Comment by deadpyxel** [comment]
That worked for me too, thanks. I'll leave this open until the maintainers can take a look, but thanks for the quick reply.

**Comment by alainbryden** [comment]
Fixed
