### ISSUE TITLE
Overview bug

### ISSUE THREAD

**Issue by RubyRezal** [alainbryden/bitburner-scripts#67]
Hi. I started running this collection of scripts a few days ago.  After a while (not sure how long, haven't timed), the Overview display gets messed up with extra spacing around Money and Stocks and a random extra underlined area next to Agi.

Killing daemon.js and running it again temporarily fixes the overview but the formatting problems come back after a while.

I'm very new to JS and not sure how to help track down and fix this.
![image](https://user-images.githubusercontent.com/1816386/159080494-8c4b0ded-c2b0-4004-83a4-ddce117e1052.png)

**Comment by alainbryden** [comment]
This happens if you change your theme in the game, the theme changer
doesn't know how to deal with extra elements added to the overview. Only
solution is to save and reload the page. Sorry!

**Comment by RubyRezal** [comment]
Ah, that is exactly what happened. Thank you for explaining.
