### ISSUE TITLE
Faction-manager throws error when no Bladeburner faction exists

### ISSUE THREAD

**Issue by TheLuBu** [alainbryden/bitburner-scripts#75]
Hi there,

in Faction-manager.js, line 241 there´s an error when the Bladeburner Bitnode is not achieved.

`factionData["Bladeburners"].joined` fails because it is undefined.

Kind regards

**Comment by halandriel** [comment]
Workaround for now: 

Add "Bladeburners" to preferredFactionOrder at the beginning of faction-manager.js
