### ISSUE TITLE
number formatting does not respect bitburner settings

### ISSUE THREAD

**Issue by steven-r** [alainbryden/bitburner-scripts#76]
I have set the number formatting in bitburner to "DE". This results in numbers like '75.000' instead of '75 000'. As some of the numbers seem to be printed in your scripts with the standard methods, and some of them not, I see lines like this:

```
Doing 'hacking' work for "Tian Di Hui" until 75.000 rep. Currently at 37.394, earning 1.506 rep/sec. (ETA: 6h 56m 13s)
``` 

I would expect something like 
```
Doing 'hacking' work for "Tian Di Hui" until 75.000k rep. Currently at 37.394k, earning 1.506 rep/sec. (ETA: 6h 56m 13s)
                                                   ^                         ^
``` 
as this is how bitburner is formatting numbers.

**Comment by alainbryden** [comment]
Making a note here that this is "solved" by adopting the fork at https://github.com/steven-r/bitburner-scripts/ , but I won't be merging for the reasons noted on PR #77 (requires external-to-BitBurner tooling).
