### ISSUE TITLE
Focus Swap Bug with faction/company work (with fix)

### ISSUE THREAD

**Issue by Skyl3lazer** [alainbryden/bitburner-scripts#8]
Hello again,

The recent issue of focus switching can be fixed by an additional parameter that wasn't documented correctly. 

`workForFaction: function (name: any, type: any, focus: boolean = true): any {`

`workForCompany: function (companyName: any, focus: boolean = true): any {`

This means on work-for-factions.js lines 486, 521, and 649, if you pass ${shouldFocusAtWork} to those commands as a 2nd/3rd argument, it won't swap focus away from what you're already doing as appropriate to the setting.  I'd PR this but I figure it's a small change, just say if you'd prefer I do that.

Thanks!

**Comment by alainbryden** [comment]
Sure, yeah as you can see O had some commented code there while I waited
for them to land on a focus api. It's all brand new

**Comment by Skyl3lazer** [comment]
Yeah, just figured I'd give you the heads up, I was talking w/ hydro about it earlier and he pointed this out to me

**Comment by alainbryden** [comment]
https://github.com/alainbryden/bitburner-scripts/commit/a4d9929a30b171e394fe3b39879b997b07b2fc4e
