### ISSUE TITLE
Missing Solver

### ISSUE THREAD

**Issue by eyoung100** [alainbryden/bitburner-scripts#82]
Version: 1.6.4
Git Pull: fbb99c17
Platform: Steam

```
[home ~/]> run daemon.js
Running script with 1 thread(s), pid 2 and args: [].
/Tasks/contractor.js.solver.js: WARNING: No solver available for contract type "Array Jumping Game II"
Full info: {"contract":"contract-261858.cct","hostname":"nwo","type":"Array Jumping Game II","data":[1,2,0,1,5,2,4,2,3,2,4]})
[home ~/]> 
```

**Comment by eyoung100** [comment]
Pulled this from // TODO in solver:

```
name: "Array Jumping Game II",
    numTries: 3,
    solver: (data: number[], ans: string): boolean => {
      const n: number = data.length;
      let reach = 0;
      let jumps = 0;
      let lastJump = -1;
      while (reach < n - 1) {
        let jumpedFrom = -1;
        for (let i = reach; i > lastJump; i--) {
          if (i + data[i] > reach) {
            reach = i + data[i];
            jumpedFrom = i;
          }
        }
        if (jumpedFrom === -1) {
          jumps = 0;
          break;
        }
        lastJump = jumpedFrom;
        jumps++;
      }
      return jumps === parseInt(ans, 10);
    },
  },
```

**Comment by steven-r** [comment]
There's another one that is bugging me: 

`/Tasks/contractor.js.solver.js: Unable to find the answer for: {"contract":"contract-32543-FulcrumSecretTechnologies.cct","hostname":"syscore","type":"HammingCodes: Encoded Binary to Integer","data":"101111101110101100"}`

Maybe a different story as this one will have another solution (and cannot be solved by hand as the array jumping game)

**Comment by alainbryden** [comment]
Note that the "solvers" in source aren't actually solving the problem, just verifying the answer the player gives, so it's not "for free" to pull a solution from there.

It'll be a while before I add solvers for all the new coding contract types. Feel free to take a stab yourself!

**Comment by alainbryden** [comment]
I'm working on the last if these now
