### ISSUE TITLE
Church of the Machine God not considered for NeuroFlux Governor

### ISSUE THREAD

**Issue by Maymne** [alainbryden/bitburner-scripts#83]
Cannot purchase any NeuroFlux Governor because the next level requires 1.426k reputation, but the best faction (Bladeburners) has insufficient rep (485.476).
  SUGGESTION: Do some work for faction Church of the Machine God to qickly earn rep for NeuroFlux Governor since it has the most favor (324.0366).

do ns.getFactionRep("Church of the Machine God")
/Temp/terminal-command.js: 5227971.642437208

I have over 5 million rep with the Church, but faction-manager.js won't use the available augmentation that's waiting right there, waiting instead for any other faction to become available, even choosing to donate rather than taking the free route.

Also I'm now noticing that there's a typo above, and the U is missing from qUickly earn rep.

**Comment by Maymne** [comment]
It appears that at one point, CotMG did not offer NFG through the API, but this is no longer the case and it's both exposed in the GUI and purchasable through the API properly now. These are lines 272-273 in faction-manager.js:

                // HACK: To work around a game bug that makes it seem like CotMG offers Neuroflux, but attempting to purchase it via the API fails.
                .filter(f => this.name != strNF || !["Church of the Machine God"].includes(f.name));

**Comment by alainbryden** [comment]
Check the discord developer channel to be sure, but I think it's a bug and hydroflame's intent is that CotMG does not offer it, because they hate all augmentations?

Either way, I can patch this up until they decide for sure one way or the other. Thanks for the report.

**Comment by Maymne** [comment]
https://github.com/danielyxie/bitburner/issues/3296

Officially tagged as an issue, but it's been one for over 2 weeks now without getting patched out.
