### ISSUE TITLE
stockmaster.js: FAIL: (0 retries remaining): ns.read('/Temp/stock-symbols.txt') somehow returned undefined or an empty string

### ISSUE THREAD

**Issue by tokumeiko** [alainbryden/bitburner-scripts#9]
this happens no matter how much I retry, and I can't figure out how getdatathroughfile failed

**Comment by alainbryden** [comment]
Reasons would either be you don't have stock market API acceess (buy it from the stockmarket page) or you don't have enough free RAM on home (buy more, kill some scripts, instructions, and/or instruct your scripts to reserve RAM at home.)
