### ISSUE TITLE
autopilot calls stockmaster even if hasTixApiAccess is not set

### ISSUE THREAD

**Issue by steven-r** [alainbryden/bitburner-scripts#91]
In this case stockmaster fails with an error in `/Temp/stock-symbols.txt.js`

**Comment by alainbryden** [comment]
Oof, gonna have to fix a lot of autopilot if you want support without SF8. It now reserves 8bil for stocks throughout. That money is wasted if you don't have stock access.

**Comment by steven-r** [comment]
Agree, but maybe put a warning while starting, that it runs wit SF8 only (or better 😀)

**Comment by alainbryden** [comment]
Found an even better solution - I noticed they added new apis for auto-purchasing WSE and TiXApi access (no SF files required), so I've enhanced stockmaster to automatically buy stock market access if the user doesn't already have it.

That means you can now always start stockmaster.js regardless of your situation.
