### ISSUE TITLE
autopilot.js is not launching work-for-faction.js

### ISSUE THREAD

**Issue by alendaris** [alainbryden/bitburner-scripts#95]
I have SFs 1.1, 4.3, 8.1, and 10.1 and am currently in BitNode 9. I seem to have hit a gap in the CheckOnRunningScripts logic because work-for-faction.js is not launching, but my manual invocation of the WFF script is getting terminated when I don't have the right arguments. gang-inGang.txt is false.

End result is that I have stocks, daemon, sleeves, spend-hashes running and accumulating money, but no significant stats/reputation development.

https://github.com/alainbryden/bitburner-scripts/blob/9ca0c461903657292704a3b2eabf6281371b7785/autopilot.js#L238-L256

**Comment by alainbryden** [comment]
Whoops, good find! Will fix asap
